/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../../custom-axios';
import type {
  CreateLibraryBody,
  GetLibraries200,
  GetLibraryAuthors200,
  GetLibraryByIdParams,
  GetLibraryItems200,
  GetLibraryItemsParams,
  GetLibrarySeries200,
  GetLibrarySeriesByIdParams,
  GetLibrarySeriesParams,
  GetPersonalizedLibraryParams,
  Library200Response,
  Library404Response,
  LibraryFilterData,
  LibraryId,
  LibraryShelf,
  SearchLibrary200,
  SearchLibraryParams,
  SeriesId,
  SeriesWithProgressAndRSS,
  UpdateLibraryByIdBody,
} from '../../models';

/**
 * Get all libraries on server.
 * @summary Get all libraries on server
 */
export const getLibraries = (signal?: AbortSignal) => {
  return customAxios<GetLibraries200>({ url: `/api/libraries`, method: 'GET', signal });
};

export const getGetLibrariesQueryKey = () => {
  return [`/api/libraries`] as const;
};

export const getGetLibrariesQueryOptions = <
  TData = Awaited<ReturnType<typeof getLibraries>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraries>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLibrariesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLibraries>>> = ({ signal }) =>
    getLibraries(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLibraries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLibrariesQueryResult = NonNullable<Awaited<ReturnType<typeof getLibraries>>>;
export type GetLibrariesQueryError = unknown;

export function useGetLibraries<TData = Awaited<ReturnType<typeof getLibraries>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraries>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraries>>,
          TError,
          Awaited<ReturnType<typeof getLibraries>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraries<TData = Awaited<ReturnType<typeof getLibraries>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraries>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraries>>,
          TError,
          Awaited<ReturnType<typeof getLibraries>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraries<TData = Awaited<ReturnType<typeof getLibraries>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraries>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all libraries on server
 */

export function useGetLibraries<TData = Awaited<ReturnType<typeof getLibraries>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraries>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLibrariesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create a new library on server.
 * @summary Create a new library on server
 */
export const createLibrary = (createLibraryBody: CreateLibraryBody, signal?: AbortSignal) => {
  return customAxios<Library200Response>({
    url: `/api/libraries`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createLibraryBody,
    signal,
  });
};

export const getCreateLibraryMutationOptions = <
  TError = Library404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLibrary>>,
    TError,
    { data: CreateLibraryBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLibrary>>,
  TError,
  { data: CreateLibraryBody },
  TContext
> => {
  const mutationKey = ['createLibrary'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLibrary>>,
    { data: CreateLibraryBody }
  > = (props) => {
    const { data } = props ?? {};

    return createLibrary(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLibraryMutationResult = NonNullable<Awaited<ReturnType<typeof createLibrary>>>;
export type CreateLibraryMutationBody = CreateLibraryBody;
export type CreateLibraryMutationError = Library404Response;

/**
 * @summary Create a new library on server
 */
export const useCreateLibrary = <TError = Library404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLibrary>>,
      TError,
      { data: CreateLibraryBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createLibrary>>,
  TError,
  { data: CreateLibraryBody },
  TContext
> => {
  const mutationOptions = getCreateLibraryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get a single library by ID on server.
 * @summary Get a single library by ID on server
 */
export const getLibraryById = (
  id: LibraryId,
  params?: GetLibraryByIdParams,
  signal?: AbortSignal
) => {
  return customAxios<Library200Response>({
    url: `/api/libraries/${id}`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetLibraryByIdQueryKey = (id: LibraryId, params?: GetLibraryByIdParams) => {
  return [`/api/libraries/${id}`, ...(params ? [params] : [])] as const;
};

export const getGetLibraryByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getLibraryById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibraryByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryById>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLibraryByIdQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLibraryById>>> = ({ signal }) =>
    getLibraryById(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLibraryById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLibraryByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLibraryById>>>;
export type GetLibraryByIdQueryError = Library404Response;

export function useGetLibraryById<
  TData = Awaited<ReturnType<typeof getLibraryById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params: undefined | GetLibraryByIdParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryById>>,
          TError,
          Awaited<ReturnType<typeof getLibraryById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryById<
  TData = Awaited<ReturnType<typeof getLibraryById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibraryByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryById>>,
          TError,
          Awaited<ReturnType<typeof getLibraryById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryById<
  TData = Awaited<ReturnType<typeof getLibraryById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibraryByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryById>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a single library by ID on server
 */

export function useGetLibraryById<
  TData = Awaited<ReturnType<typeof getLibraryById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibraryByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryById>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLibraryByIdQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update a single library by ID on server.
 * @summary Update a single library by ID on server
 */
export const updateLibraryById = (id: LibraryId, updateLibraryByIdBody: UpdateLibraryByIdBody) => {
  return customAxios<Library200Response>({
    url: `/api/libraries/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateLibraryByIdBody,
  });
};

export const getUpdateLibraryByIdMutationOptions = <
  TError = Library404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLibraryById>>,
    TError,
    { id: LibraryId; data: UpdateLibraryByIdBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateLibraryById>>,
  TError,
  { id: LibraryId; data: UpdateLibraryByIdBody },
  TContext
> => {
  const mutationKey = ['updateLibraryById'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateLibraryById>>,
    { id: LibraryId; data: UpdateLibraryByIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateLibraryById(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateLibraryByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateLibraryById>>
>;
export type UpdateLibraryByIdMutationBody = UpdateLibraryByIdBody;
export type UpdateLibraryByIdMutationError = Library404Response;

/**
 * @summary Update a single library by ID on server
 */
export const useUpdateLibraryById = <TError = Library404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateLibraryById>>,
      TError,
      { id: LibraryId; data: UpdateLibraryByIdBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateLibraryById>>,
  TError,
  { id: LibraryId; data: UpdateLibraryByIdBody },
  TContext
> => {
  const mutationOptions = getUpdateLibraryByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete a single library by ID on server and return the deleted object.
 * @summary Delete a single library by ID on server
 */
export const deleteLibraryById = (id: LibraryId) => {
  return customAxios<Library200Response>({ url: `/api/libraries/${id}`, method: 'DELETE' });
};

export const getDeleteLibraryByIdMutationOptions = <
  TError = Library404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteLibraryById>>,
    TError,
    { id: LibraryId },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteLibraryById>>,
  TError,
  { id: LibraryId },
  TContext
> => {
  const mutationKey = ['deleteLibraryById'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteLibraryById>>,
    { id: LibraryId }
  > = (props) => {
    const { id } = props ?? {};

    return deleteLibraryById(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteLibraryByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteLibraryById>>
>;

export type DeleteLibraryByIdMutationError = Library404Response;

/**
 * @summary Delete a single library by ID on server
 */
export const useDeleteLibraryById = <TError = Library404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteLibraryById>>,
      TError,
      { id: LibraryId },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteLibraryById>>,
  TError,
  { id: LibraryId },
  TContext
> => {
  const mutationOptions = getDeleteLibraryByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get all authors in a library by ID on server.
 * @summary Get all authors in a library
 */
export const getLibraryAuthors = (id: LibraryId, signal?: AbortSignal) => {
  return customAxios<GetLibraryAuthors200>({
    url: `/api/libraries/${id}/authors`,
    method: 'GET',
    signal,
  });
};

export const getGetLibraryAuthorsQueryKey = (id: LibraryId) => {
  return [`/api/libraries/${id}/authors`] as const;
};

export const getGetLibraryAuthorsQueryOptions = <
  TData = Awaited<ReturnType<typeof getLibraryAuthors>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryAuthors>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLibraryAuthorsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLibraryAuthors>>> = ({ signal }) =>
    getLibraryAuthors(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLibraryAuthors>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLibraryAuthorsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLibraryAuthors>>
>;
export type GetLibraryAuthorsQueryError = Library404Response;

export function useGetLibraryAuthors<
  TData = Awaited<ReturnType<typeof getLibraryAuthors>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryAuthors>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryAuthors>>,
          TError,
          Awaited<ReturnType<typeof getLibraryAuthors>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryAuthors<
  TData = Awaited<ReturnType<typeof getLibraryAuthors>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryAuthors>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryAuthors>>,
          TError,
          Awaited<ReturnType<typeof getLibraryAuthors>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryAuthors<
  TData = Awaited<ReturnType<typeof getLibraryAuthors>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryAuthors>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all authors in a library
 */

export function useGetLibraryAuthors<
  TData = Awaited<ReturnType<typeof getLibraryAuthors>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryAuthors>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLibraryAuthorsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get items in a library by ID on server.
 * @summary Get items in a library
 */
export const getLibraryItems = (
  id: LibraryId,
  params?: GetLibraryItemsParams,
  signal?: AbortSignal
) => {
  return customAxios<GetLibraryItems200>({
    url: `/api/libraries/${id}/items`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetLibraryItemsQueryKey = (id: LibraryId, params?: GetLibraryItemsParams) => {
  return [`/api/libraries/${id}/items`, ...(params ? [params] : [])] as const;
};

export const getGetLibraryItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof getLibraryItems>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibraryItemsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItems>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLibraryItemsQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLibraryItems>>> = ({ signal }) =>
    getLibraryItems(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLibraryItems>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLibraryItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getLibraryItems>>>;
export type GetLibraryItemsQueryError = Library404Response;

export function useGetLibraryItems<
  TData = Awaited<ReturnType<typeof getLibraryItems>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params: undefined | GetLibraryItemsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItems>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryItems>>,
          TError,
          Awaited<ReturnType<typeof getLibraryItems>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryItems<
  TData = Awaited<ReturnType<typeof getLibraryItems>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibraryItemsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItems>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryItems>>,
          TError,
          Awaited<ReturnType<typeof getLibraryItems>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryItems<
  TData = Awaited<ReturnType<typeof getLibraryItems>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibraryItemsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItems>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get items in a library
 */

export function useGetLibraryItems<
  TData = Awaited<ReturnType<typeof getLibraryItems>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibraryItemsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItems>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLibraryItemsQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Delete all items with issues in a library by library ID on the server. This only removes the items from the ABS database and does not delete media files.
 * @summary Delete items with issues in a library.
 */
export const deleteLibraryIssues = (id: LibraryId) => {
  return customAxios<string>({ url: `/api/libraries/${id}/issues`, method: 'DELETE' });
};

export const getDeleteLibraryIssuesMutationOptions = <
  TError = Library404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteLibraryIssues>>,
    TError,
    { id: LibraryId },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteLibraryIssues>>,
  TError,
  { id: LibraryId },
  TContext
> => {
  const mutationKey = ['deleteLibraryIssues'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteLibraryIssues>>,
    { id: LibraryId }
  > = (props) => {
    const { id } = props ?? {};

    return deleteLibraryIssues(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteLibraryIssuesMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteLibraryIssues>>
>;

export type DeleteLibraryIssuesMutationError = Library404Response;

/**
 * @summary Delete items with issues in a library.
 */
export const useDeleteLibraryIssues = <TError = Library404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteLibraryIssues>>,
      TError,
      { id: LibraryId },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteLibraryIssues>>,
  TError,
  { id: LibraryId },
  TContext
> => {
  const mutationOptions = getDeleteLibraryIssuesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get series in a library. Filtering and sorting can be applied.
 * @summary Get library series
 */
export const getLibrarySeries = (
  id: LibraryId,
  params?: GetLibrarySeriesParams,
  signal?: AbortSignal
) => {
  return customAxios<GetLibrarySeries200>({
    url: `/api/libraries/${id}/series`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetLibrarySeriesQueryKey = (id: LibraryId, params?: GetLibrarySeriesParams) => {
  return [`/api/libraries/${id}/series`, ...(params ? [params] : [])] as const;
};

export const getGetLibrarySeriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getLibrarySeries>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibrarySeriesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeries>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLibrarySeriesQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLibrarySeries>>> = ({ signal }) =>
    getLibrarySeries(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLibrarySeries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLibrarySeriesQueryResult = NonNullable<Awaited<ReturnType<typeof getLibrarySeries>>>;
export type GetLibrarySeriesQueryError = Library404Response;

export function useGetLibrarySeries<
  TData = Awaited<ReturnType<typeof getLibrarySeries>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params: undefined | GetLibrarySeriesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeries>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibrarySeries>>,
          TError,
          Awaited<ReturnType<typeof getLibrarySeries>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibrarySeries<
  TData = Awaited<ReturnType<typeof getLibrarySeries>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibrarySeriesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeries>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibrarySeries>>,
          TError,
          Awaited<ReturnType<typeof getLibrarySeries>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibrarySeries<
  TData = Awaited<ReturnType<typeof getLibrarySeries>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibrarySeriesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeries>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get library series
 */

export function useGetLibrarySeries<
  TData = Awaited<ReturnType<typeof getLibrarySeries>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetLibrarySeriesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeries>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLibrarySeriesQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a single series in a library by ID on server. This endpoint is deprecated and `/api/series/{id}` should be used instead.
 * @deprecated
 * @summary Get single series in library
 */
export const getLibrarySeriesById = (
  id: LibraryId,
  seriesId: SeriesId,
  params?: GetLibrarySeriesByIdParams,
  signal?: AbortSignal
) => {
  return customAxios<SeriesWithProgressAndRSS>({
    url: `/api/libraries/${id}/series/${seriesId}`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetLibrarySeriesByIdQueryKey = (
  id: LibraryId,
  seriesId: SeriesId,
  params?: GetLibrarySeriesByIdParams
) => {
  return [`/api/libraries/${id}/series/${seriesId}`, ...(params ? [params] : [])] as const;
};

export const getGetLibrarySeriesByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getLibrarySeriesById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  seriesId: SeriesId,
  params?: GetLibrarySeriesByIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeriesById>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLibrarySeriesByIdQueryKey(id, seriesId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLibrarySeriesById>>> = ({ signal }) =>
    getLibrarySeriesById(id, seriesId, params, signal);

  return { queryKey, queryFn, enabled: !!(id && seriesId), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLibrarySeriesById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLibrarySeriesByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLibrarySeriesById>>
>;
export type GetLibrarySeriesByIdQueryError = Library404Response;

export function useGetLibrarySeriesById<
  TData = Awaited<ReturnType<typeof getLibrarySeriesById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  seriesId: SeriesId,
  params: undefined | GetLibrarySeriesByIdParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeriesById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibrarySeriesById>>,
          TError,
          Awaited<ReturnType<typeof getLibrarySeriesById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibrarySeriesById<
  TData = Awaited<ReturnType<typeof getLibrarySeriesById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  seriesId: SeriesId,
  params?: GetLibrarySeriesByIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeriesById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibrarySeriesById>>,
          TError,
          Awaited<ReturnType<typeof getLibrarySeriesById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibrarySeriesById<
  TData = Awaited<ReturnType<typeof getLibrarySeriesById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  seriesId: SeriesId,
  params?: GetLibrarySeriesByIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeriesById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @deprecated
 * @summary Get single series in library
 */

export function useGetLibrarySeriesById<
  TData = Awaited<ReturnType<typeof getLibrarySeriesById>>,
  TError = Library404Response,
>(
  id: LibraryId,
  seriesId: SeriesId,
  params?: GetLibrarySeriesByIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibrarySeriesById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLibrarySeriesByIdQueryOptions(id, seriesId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Search library by ID on server.
 * @summary Search library
 */
export const searchLibrary = (id: LibraryId, params: SearchLibraryParams, signal?: AbortSignal) => {
  return customAxios<SearchLibrary200>({
    url: `/api/libraries/${id}/search`,
    method: 'GET',
    params,
    signal,
  });
};

export const getSearchLibraryQueryKey = (id: LibraryId, params: SearchLibraryParams) => {
  return [`/api/libraries/${id}/search`, ...(params ? [params] : [])] as const;
};

export const getSearchLibraryQueryOptions = <
  TData = Awaited<ReturnType<typeof searchLibrary>>,
  TError = string | Library404Response,
>(
  id: LibraryId,
  params: SearchLibraryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLibrary>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchLibraryQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchLibrary>>> = ({ signal }) =>
    searchLibrary(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchLibrary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchLibraryQueryResult = NonNullable<Awaited<ReturnType<typeof searchLibrary>>>;
export type SearchLibraryQueryError = string | Library404Response;

export function useSearchLibrary<
  TData = Awaited<ReturnType<typeof searchLibrary>>,
  TError = string | Library404Response,
>(
  id: LibraryId,
  params: SearchLibraryParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLibrary>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchLibrary>>,
          TError,
          Awaited<ReturnType<typeof searchLibrary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchLibrary<
  TData = Awaited<ReturnType<typeof searchLibrary>>,
  TError = string | Library404Response,
>(
  id: LibraryId,
  params: SearchLibraryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLibrary>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchLibrary>>,
          TError,
          Awaited<ReturnType<typeof searchLibrary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchLibrary<
  TData = Awaited<ReturnType<typeof searchLibrary>>,
  TError = string | Library404Response,
>(
  id: LibraryId,
  params: SearchLibraryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLibrary>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Search library
 */

export function useSearchLibrary<
  TData = Awaited<ReturnType<typeof searchLibrary>>,
  TError = string | Library404Response,
>(
  id: LibraryId,
  params: SearchLibraryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchLibrary>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchLibraryQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get filter data for library by ID on server.
 * @summary Get filter data for library
 */
export const getLibraryFilterData = (id: LibraryId, signal?: AbortSignal) => {
  return customAxios<LibraryFilterData>({
    url: `/api/libraries/${id}/filterdata`,
    method: 'GET',
    signal,
  });
};

export const getGetLibraryFilterDataQueryKey = (id: LibraryId) => {
  return [`/api/libraries/${id}/filterdata`] as const;
};

export const getGetLibraryFilterDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getLibraryFilterData>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibraryFilterData>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLibraryFilterDataQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLibraryFilterData>>> = ({ signal }) =>
    getLibraryFilterData(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLibraryFilterData>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLibraryFilterDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLibraryFilterData>>
>;
export type GetLibraryFilterDataQueryError = Library404Response;

export function useGetLibraryFilterData<
  TData = Awaited<ReturnType<typeof getLibraryFilterData>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibraryFilterData>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryFilterData>>,
          TError,
          Awaited<ReturnType<typeof getLibraryFilterData>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryFilterData<
  TData = Awaited<ReturnType<typeof getLibraryFilterData>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibraryFilterData>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryFilterData>>,
          TError,
          Awaited<ReturnType<typeof getLibraryFilterData>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryFilterData<
  TData = Awaited<ReturnType<typeof getLibraryFilterData>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibraryFilterData>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get filter data for library
 */

export function useGetLibraryFilterData<
  TData = Awaited<ReturnType<typeof getLibraryFilterData>>,
  TError = Library404Response,
>(
  id: LibraryId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLibraryFilterData>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLibraryFilterDataQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get personalized library (home page).
 * @summary Get personalized library (home page).
 */
export const getPersonalizedLibrary = (
  id: LibraryId,
  params?: GetPersonalizedLibraryParams,
  signal?: AbortSignal
) => {
  return customAxios<LibraryShelf[]>({
    url: `/api/libraries/${id}/personalized`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetPersonalizedLibraryQueryKey = (
  id: LibraryId,
  params?: GetPersonalizedLibraryParams
) => {
  return [`/api/libraries/${id}/personalized`, ...(params ? [params] : [])] as const;
};

export const getGetPersonalizedLibraryQueryOptions = <
  TData = Awaited<ReturnType<typeof getPersonalizedLibrary>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetPersonalizedLibraryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPersonalizedLibrary>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPersonalizedLibraryQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPersonalizedLibrary>>> = ({ signal }) =>
    getPersonalizedLibrary(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPersonalizedLibrary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPersonalizedLibraryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPersonalizedLibrary>>
>;
export type GetPersonalizedLibraryQueryError = Library404Response;

export function useGetPersonalizedLibrary<
  TData = Awaited<ReturnType<typeof getPersonalizedLibrary>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params: undefined | GetPersonalizedLibraryParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPersonalizedLibrary>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPersonalizedLibrary>>,
          TError,
          Awaited<ReturnType<typeof getPersonalizedLibrary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPersonalizedLibrary<
  TData = Awaited<ReturnType<typeof getPersonalizedLibrary>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetPersonalizedLibraryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPersonalizedLibrary>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPersonalizedLibrary>>,
          TError,
          Awaited<ReturnType<typeof getPersonalizedLibrary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPersonalizedLibrary<
  TData = Awaited<ReturnType<typeof getPersonalizedLibrary>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetPersonalizedLibraryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPersonalizedLibrary>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get personalized library (home page).
 */

export function useGetPersonalizedLibrary<
  TData = Awaited<ReturnType<typeof getPersonalizedLibrary>>,
  TError = Library404Response,
>(
  id: LibraryId,
  params?: GetPersonalizedLibraryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPersonalizedLibrary>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPersonalizedLibraryQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
