/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../../custom-axios';
import type {
  AddAuthorImageByIdParams,
  Author,
  Author404Response,
  AuthorId,
  DeleteAuthorImageByIdParams,
  GetAuthorByIdParams,
  GetAuthorImageByIdBody,
  GetAuthorImageByIdParams,
  ImageUrl,
  MatchAuthorById200,
  MatchAuthorByIdBody,
  UpdateAuthorById200,
  UpdateAuthorByIdBody,
  UpdateAuthorImageByIdBody,
  UpdateAuthorImageByIdParams,
} from '../../models';

/**
 * Get an author by ID. The author's books and series can be included in the response.
 * @summary Get an author by ID
 */
export const getAuthorById = (id: AuthorId, params?: GetAuthorByIdParams, signal?: AbortSignal) => {
  return customAxios<Author>({ url: `/api/authors/${id}`, method: 'GET', params, signal });
};

export const getGetAuthorByIdQueryKey = (id: AuthorId, params?: GetAuthorByIdParams) => {
  return [`/api/authors/${id}`, ...(params ? [params] : [])] as const;
};

export const getGetAuthorByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthorById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  params?: GetAuthorByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthorById>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthorByIdQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthorById>>> = ({ signal }) =>
    getAuthorById(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthorById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthorByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthorById>>>;
export type GetAuthorByIdQueryError = Author404Response;

export function useGetAuthorById<
  TData = Awaited<ReturnType<typeof getAuthorById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  params: undefined | GetAuthorByIdParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthorById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthorById>>,
          TError,
          Awaited<ReturnType<typeof getAuthorById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthorById<
  TData = Awaited<ReturnType<typeof getAuthorById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  params?: GetAuthorByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthorById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthorById>>,
          TError,
          Awaited<ReturnType<typeof getAuthorById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthorById<
  TData = Awaited<ReturnType<typeof getAuthorById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  params?: GetAuthorByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthorById>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get an author by ID
 */

export function useGetAuthorById<
  TData = Awaited<ReturnType<typeof getAuthorById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  params?: GetAuthorByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthorById>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthorByIdQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update an author by ID. The author's name and description can be updated. This endpoint will merge two authors if the new author name matches another author name in the database.
 * @summary Update an author by ID
 */
export const updateAuthorById = (id: AuthorId, updateAuthorByIdBody: UpdateAuthorByIdBody) => {
  return customAxios<UpdateAuthorById200>({
    url: `/api/authors/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAuthorByIdBody,
  });
};

export const getUpdateAuthorByIdMutationOptions = <
  TError = Author404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAuthorById>>,
    TError,
    { id: AuthorId; data: UpdateAuthorByIdBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAuthorById>>,
  TError,
  { id: AuthorId; data: UpdateAuthorByIdBody },
  TContext
> => {
  const mutationKey = ['updateAuthorById'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAuthorById>>,
    { id: AuthorId; data: UpdateAuthorByIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateAuthorById(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAuthorByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAuthorById>>
>;
export type UpdateAuthorByIdMutationBody = UpdateAuthorByIdBody;
export type UpdateAuthorByIdMutationError = Author404Response;

/**
 * @summary Update an author by ID
 */
export const useUpdateAuthorById = <TError = Author404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAuthorById>>,
      TError,
      { id: AuthorId; data: UpdateAuthorByIdBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateAuthorById>>,
  TError,
  { id: AuthorId; data: UpdateAuthorByIdBody },
  TContext
> => {
  const mutationOptions = getUpdateAuthorByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete an author by ID. This will remove the author from all books.
 * @summary Delete an author by ID
 */
export const deleteAuthorById = (id: AuthorId) => {
  return customAxios<string>({ url: `/api/authors/${id}`, method: 'DELETE' });
};

export const getDeleteAuthorByIdMutationOptions = <
  TError = Author404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAuthorById>>,
    TError,
    { id: AuthorId },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAuthorById>>,
  TError,
  { id: AuthorId },
  TContext
> => {
  const mutationKey = ['deleteAuthorById'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAuthorById>>,
    { id: AuthorId }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAuthorById(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAuthorByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAuthorById>>
>;

export type DeleteAuthorByIdMutationError = Author404Response;

/**
 * @summary Delete an author by ID
 */
export const useDeleteAuthorById = <TError = Author404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAuthorById>>,
      TError,
      { id: AuthorId },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAuthorById>>,
  TError,
  { id: AuthorId },
  TContext
> => {
  const mutationOptions = getDeleteAuthorByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get an author image by author ID. The image will be returned in the requested format and size.
 * @summary Get an author image by author ID
 */
export const getAuthorImageById = (
  id: AuthorId,
  getAuthorImageByIdBody?: GetAuthorImageByIdBody,
  params?: GetAuthorImageByIdParams,
  signal?: AbortSignal
) => {
  return customAxios<Blob>({
    url: `/api/authors/${id}/image`,
    method: 'GET',
    headers: { 'Content-Type': 'application/json' },
    params,
    responseType: 'blob',
    signal,
  });
};

export const getGetAuthorImageByIdQueryKey = (
  id: AuthorId,
  getAuthorImageByIdBody?: GetAuthorImageByIdBody,
  params?: GetAuthorImageByIdParams
) => {
  return [`/api/authors/${id}/image`, ...(params ? [params] : []), getAuthorImageByIdBody] as const;
};

export const getGetAuthorImageByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthorImageById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  getAuthorImageByIdBody?: GetAuthorImageByIdBody,
  params?: GetAuthorImageByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthorImageById>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthorImageByIdQueryKey(id, getAuthorImageByIdBody, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthorImageById>>> = ({ signal }) =>
    getAuthorImageById(id, getAuthorImageByIdBody, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthorImageById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthorImageByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthorImageById>>
>;
export type GetAuthorImageByIdQueryError = Author404Response;

export function useGetAuthorImageById<
  TData = Awaited<ReturnType<typeof getAuthorImageById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  getAuthorImageByIdBody: undefined | GetAuthorImageByIdBody,
  params: undefined | GetAuthorImageByIdParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthorImageById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthorImageById>>,
          TError,
          Awaited<ReturnType<typeof getAuthorImageById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthorImageById<
  TData = Awaited<ReturnType<typeof getAuthorImageById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  getAuthorImageByIdBody?: GetAuthorImageByIdBody,
  params?: GetAuthorImageByIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthorImageById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthorImageById>>,
          TError,
          Awaited<ReturnType<typeof getAuthorImageById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthorImageById<
  TData = Awaited<ReturnType<typeof getAuthorImageById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  getAuthorImageByIdBody?: GetAuthorImageByIdBody,
  params?: GetAuthorImageByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthorImageById>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get an author image by author ID
 */

export function useGetAuthorImageById<
  TData = Awaited<ReturnType<typeof getAuthorImageById>>,
  TError = Author404Response,
>(
  id: AuthorId,
  getAuthorImageByIdBody?: GetAuthorImageByIdBody,
  params?: GetAuthorImageByIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthorImageById>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthorImageByIdQueryOptions(
    id,
    getAuthorImageByIdBody,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Add an author image to the server. The image will be downloaded from the provided URL and stored on the server.
 * @summary Add an author image to the server
 */
export const addAuthorImageById = (
  id: AuthorId,
  imageUrl: ImageUrl,
  params?: AddAuthorImageByIdParams,
  signal?: AbortSignal
) => {
  return customAxios<Blob>({
    url: `/api/authors/${id}/image`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: imageUrl,
    params,
    responseType: 'blob',
    signal,
  });
};

export const getAddAuthorImageByIdMutationOptions = <
  TError = Author404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addAuthorImageById>>,
    TError,
    { id: AuthorId; data: ImageUrl; params?: AddAuthorImageByIdParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addAuthorImageById>>,
  TError,
  { id: AuthorId; data: ImageUrl; params?: AddAuthorImageByIdParams },
  TContext
> => {
  const mutationKey = ['addAuthorImageById'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addAuthorImageById>>,
    { id: AuthorId; data: ImageUrl; params?: AddAuthorImageByIdParams }
  > = (props) => {
    const { id, data, params } = props ?? {};

    return addAuthorImageById(id, data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddAuthorImageByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof addAuthorImageById>>
>;
export type AddAuthorImageByIdMutationBody = ImageUrl;
export type AddAuthorImageByIdMutationError = Author404Response;

/**
 * @summary Add an author image to the server
 */
export const useAddAuthorImageById = <TError = Author404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addAuthorImageById>>,
      TError,
      { id: AuthorId; data: ImageUrl; params?: AddAuthorImageByIdParams },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof addAuthorImageById>>,
  TError,
  { id: AuthorId; data: ImageUrl; params?: AddAuthorImageByIdParams },
  TContext
> => {
  const mutationOptions = getAddAuthorImageByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Update an author image by author ID. The image will be resized if the width, height, or format is provided.
 * @summary Update an author image by author ID
 */
export const updateAuthorImageById = (
  id: AuthorId,
  updateAuthorImageByIdBody: UpdateAuthorImageByIdBody,
  params?: UpdateAuthorImageByIdParams
) => {
  return customAxios<Blob>({
    url: `/api/authors/${id}/image`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAuthorImageByIdBody,
    params,
    responseType: 'blob',
  });
};

export const getUpdateAuthorImageByIdMutationOptions = <
  TError = Author404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAuthorImageById>>,
    TError,
    { id: AuthorId; data: UpdateAuthorImageByIdBody; params?: UpdateAuthorImageByIdParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAuthorImageById>>,
  TError,
  { id: AuthorId; data: UpdateAuthorImageByIdBody; params?: UpdateAuthorImageByIdParams },
  TContext
> => {
  const mutationKey = ['updateAuthorImageById'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAuthorImageById>>,
    { id: AuthorId; data: UpdateAuthorImageByIdBody; params?: UpdateAuthorImageByIdParams }
  > = (props) => {
    const { id, data, params } = props ?? {};

    return updateAuthorImageById(id, data, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAuthorImageByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAuthorImageById>>
>;
export type UpdateAuthorImageByIdMutationBody = UpdateAuthorImageByIdBody;
export type UpdateAuthorImageByIdMutationError = Author404Response;

/**
 * @summary Update an author image by author ID
 */
export const useUpdateAuthorImageById = <TError = Author404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAuthorImageById>>,
      TError,
      { id: AuthorId; data: UpdateAuthorImageByIdBody; params?: UpdateAuthorImageByIdParams },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateAuthorImageById>>,
  TError,
  { id: AuthorId; data: UpdateAuthorImageByIdBody; params?: UpdateAuthorImageByIdParams },
  TContext
> => {
  const mutationOptions = getUpdateAuthorImageByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete an author image by author ID. This will remove the image from the server and the database.
 * @summary Delete an author image by author ID
 */
export const deleteAuthorImageById = (id: AuthorId, params?: DeleteAuthorImageByIdParams) => {
  return customAxios<void>({ url: `/api/authors/${id}/image`, method: 'DELETE', params });
};

export const getDeleteAuthorImageByIdMutationOptions = <
  TError = Author404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAuthorImageById>>,
    TError,
    { id: AuthorId; params?: DeleteAuthorImageByIdParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAuthorImageById>>,
  TError,
  { id: AuthorId; params?: DeleteAuthorImageByIdParams },
  TContext
> => {
  const mutationKey = ['deleteAuthorImageById'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAuthorImageById>>,
    { id: AuthorId; params?: DeleteAuthorImageByIdParams }
  > = (props) => {
    const { id, params } = props ?? {};

    return deleteAuthorImageById(id, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAuthorImageByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAuthorImageById>>
>;

export type DeleteAuthorImageByIdMutationError = Author404Response;

/**
 * @summary Delete an author image by author ID
 */
export const useDeleteAuthorImageById = <TError = Author404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAuthorImageById>>,
      TError,
      { id: AuthorId; params?: DeleteAuthorImageByIdParams },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAuthorImageById>>,
  TError,
  { id: AuthorId; params?: DeleteAuthorImageByIdParams },
  TContext
> => {
  const mutationOptions = getDeleteAuthorImageByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Match the author against Audible using quick match. Quick match updates the author's description and image (if no image already existed) with information from audible. Either `asin` or `q` must be provided, with `asin` taking priority if both are provided.
 * @summary Match the author against Audible using quick match
 */
export const matchAuthorById = (
  id: AuthorId,
  matchAuthorByIdBody: MatchAuthorByIdBody,
  signal?: AbortSignal
) => {
  return customAxios<MatchAuthorById200>({
    url: `/api/authors/${id}/match`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: matchAuthorByIdBody,
    signal,
  });
};

export const getMatchAuthorByIdMutationOptions = <
  TError = Author404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof matchAuthorById>>,
    TError,
    { id: AuthorId; data: MatchAuthorByIdBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof matchAuthorById>>,
  TError,
  { id: AuthorId; data: MatchAuthorByIdBody },
  TContext
> => {
  const mutationKey = ['matchAuthorById'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof matchAuthorById>>,
    { id: AuthorId; data: MatchAuthorByIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return matchAuthorById(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MatchAuthorByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof matchAuthorById>>
>;
export type MatchAuthorByIdMutationBody = MatchAuthorByIdBody;
export type MatchAuthorByIdMutationError = Author404Response;

/**
 * @summary Match the author against Audible using quick match
 */
export const useMatchAuthorById = <TError = Author404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof matchAuthorById>>,
      TError,
      { id: AuthorId; data: MatchAuthorByIdBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof matchAuthorById>>,
  TError,
  { id: AuthorId; data: MatchAuthorByIdBody },
  TContext
> => {
  const mutationOptions = getMatchAuthorByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
