/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../../custom-axios';
import type {
  CloseSessionParams,
  GetSessions200,
  GetSessionsParams,
  PlaybackSession,
  PlaybackSessionExpanded,
  PlaybackSessionId,
  SyncOpenSessionBody,
} from '../../models';

/**
 * Sync an open session.
 * @summary Sync an open session.
 */
export const syncOpenSession = (
  id: PlaybackSessionId,
  syncOpenSessionBody: SyncOpenSessionBody,
  signal?: AbortSignal
) => {
  return customAxios<string>({
    url: `/api/session/${id}/sync`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: syncOpenSessionBody,
    signal,
  });
};

export const getSyncOpenSessionMutationOptions = <TError = string, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof syncOpenSession>>,
    TError,
    { id: PlaybackSessionId; data: SyncOpenSessionBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof syncOpenSession>>,
  TError,
  { id: PlaybackSessionId; data: SyncOpenSessionBody },
  TContext
> => {
  const mutationKey = ['syncOpenSession'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof syncOpenSession>>,
    { id: PlaybackSessionId; data: SyncOpenSessionBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return syncOpenSession(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SyncOpenSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof syncOpenSession>>
>;
export type SyncOpenSessionMutationBody = SyncOpenSessionBody;
export type SyncOpenSessionMutationError = string;

/**
 * @summary Sync an open session.
 */
export const useSyncOpenSession = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof syncOpenSession>>,
      TError,
      { id: PlaybackSessionId; data: SyncOpenSessionBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof syncOpenSession>>,
  TError,
  { id: PlaybackSessionId; data: SyncOpenSessionBody },
  TContext
> => {
  const mutationOptions = getSyncOpenSessionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Deletes a listening session.
 * @summary Delets a listening session.
 */
export const deleteSession = (id: PlaybackSessionId) => {
  return customAxios<string>({ url: `/api/sessions/${id}`, method: 'DELETE' });
};

export const getDeleteSessionMutationOptions = <TError = string, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSession>>,
    TError,
    { id: PlaybackSessionId },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSession>>,
  TError,
  { id: PlaybackSessionId },
  TContext
> => {
  const mutationKey = ['deleteSession'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSession>>,
    { id: PlaybackSessionId }
  > = (props) => {
    const { id } = props ?? {};

    return deleteSession(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSessionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSession>>>;

export type DeleteSessionMutationError = string;

/**
 * @summary Delets a listening session.
 */
export const useDeleteSession = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSession>>,
      TError,
      { id: PlaybackSessionId },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSession>>,
  TError,
  { id: PlaybackSessionId },
  TContext
> => {
  const mutationOptions = getDeleteSessionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Close a listening session.
 * @summary Close a listening session.
 */
export const closeSession = (
  id: PlaybackSessionId,
  params?: CloseSessionParams,
  signal?: AbortSignal
) => {
  return customAxios<string>({ url: `/api/session/${id}/close`, method: 'POST', params, signal });
};

export const getCloseSessionMutationOptions = <TError = string, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof closeSession>>,
    TError,
    { id: PlaybackSessionId; params?: CloseSessionParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof closeSession>>,
  TError,
  { id: PlaybackSessionId; params?: CloseSessionParams },
  TContext
> => {
  const mutationKey = ['closeSession'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof closeSession>>,
    { id: PlaybackSessionId; params?: CloseSessionParams }
  > = (props) => {
    const { id, params } = props ?? {};

    return closeSession(id, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type CloseSessionMutationResult = NonNullable<Awaited<ReturnType<typeof closeSession>>>;

export type CloseSessionMutationError = string;

/**
 * @summary Close a listening session.
 */
export const useCloseSession = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof closeSession>>,
      TError,
      { id: PlaybackSessionId; params?: CloseSessionParams },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof closeSession>>,
  TError,
  { id: PlaybackSessionId; params?: CloseSessionParams },
  TContext
> => {
  const mutationOptions = getCloseSessionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get a listening session.
 * @summary Get a listening session.
 */
export const getSession = (id: PlaybackSessionId, signal?: AbortSignal) => {
  return customAxios<PlaybackSessionExpanded>({ url: `/api/session/${id}`, method: 'GET', signal });
};

export const getGetSessionQueryKey = (id: PlaybackSessionId) => {
  return [`/api/session/${id}`] as const;
};

export const getGetSessionQueryOptions = <
  TData = Awaited<ReturnType<typeof getSession>>,
  TError = string,
>(
  id: PlaybackSessionId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSessionQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) =>
    getSession(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSession>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>;
export type GetSessionQueryError = string;

export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = string>(
  id: PlaybackSessionId,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSession>>,
          TError,
          Awaited<ReturnType<typeof getSession>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = string>(
  id: PlaybackSessionId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSession>>,
          TError,
          Awaited<ReturnType<typeof getSession>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = string>(
  id: PlaybackSessionId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a listening session.
 */

export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = string>(
  id: PlaybackSessionId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSessionQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get all listening sessions.
 * @summary Get all listening sessions.
 */
export const getSessions = (params?: GetSessionsParams, signal?: AbortSignal) => {
  return customAxios<GetSessions200>({ url: `/api/sessions`, method: 'GET', params, signal });
};

export const getGetSessionsQueryKey = (params?: GetSessionsParams) => {
  return [`/api/sessions`, ...(params ? [params] : [])] as const;
};

export const getGetSessionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSessions>>,
  TError = string,
>(
  params?: GetSessionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSessionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSessions>>> = ({ signal }) =>
    getSessions(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSessions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getSessions>>>;
export type GetSessionsQueryError = string;

export function useGetSessions<TData = Awaited<ReturnType<typeof getSessions>>, TError = string>(
  params: undefined | GetSessionsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessions>>,
          TError,
          Awaited<ReturnType<typeof getSessions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSessions<TData = Awaited<ReturnType<typeof getSessions>>, TError = string>(
  params?: GetSessionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessions>>,
          TError,
          Awaited<ReturnType<typeof getSessions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSessions<TData = Awaited<ReturnType<typeof getSessions>>, TError = string>(
  params?: GetSessionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all listening sessions.
 */

export function useGetSessions<TData = Awaited<ReturnType<typeof getSessions>>, TError = string>(
  params?: GetSessionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessions>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSessionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create a local session.
 * @summary Create a local session.
 */
export const createLocalSession = (playbackSession: PlaybackSession, signal?: AbortSignal) => {
  return customAxios<string>({
    url: `/api/session/local`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: playbackSession,
    signal,
  });
};

export const getCreateLocalSessionMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLocalSession>>,
    TError,
    { data: PlaybackSession },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLocalSession>>,
  TError,
  { data: PlaybackSession },
  TContext
> => {
  const mutationKey = ['createLocalSession'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLocalSession>>,
    { data: PlaybackSession }
  > = (props) => {
    const { data } = props ?? {};

    return createLocalSession(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLocalSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLocalSession>>
>;
export type CreateLocalSessionMutationBody = PlaybackSession;
export type CreateLocalSessionMutationError = string;

/**
 * @summary Create a local session.
 */
export const useCreateLocalSession = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLocalSession>>,
      TError,
      { data: PlaybackSession },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createLocalSession>>,
  TError,
  { data: PlaybackSession },
  TContext
> => {
  const mutationOptions = getCreateLocalSessionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Create a local session for all users.
 * @summary Create a local session for all users.
 */
export const createLocalSessionAll = (playbackSession: PlaybackSession[], signal?: AbortSignal) => {
  return customAxios<string>({
    url: `/api/local/session/local-all`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: playbackSession,
    signal,
  });
};

export const getCreateLocalSessionAllMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLocalSessionAll>>,
    TError,
    { data: PlaybackSession[] },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLocalSessionAll>>,
  TError,
  { data: PlaybackSession[] },
  TContext
> => {
  const mutationKey = ['createLocalSessionAll'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLocalSessionAll>>,
    { data: PlaybackSession[] }
  > = (props) => {
    const { data } = props ?? {};

    return createLocalSessionAll(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLocalSessionAllMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLocalSessionAll>>
>;
export type CreateLocalSessionAllMutationBody = PlaybackSession[];
export type CreateLocalSessionAllMutationError = string;

/**
 * @summary Create a local session for all users.
 */
export const useCreateLocalSessionAll = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLocalSessionAll>>,
      TError,
      { data: PlaybackSession[] },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createLocalSessionAll>>,
  TError,
  { data: PlaybackSession[] },
  TContext
> => {
  const mutationOptions = getCreateLocalSessionAllMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
