/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../../custom-axios';
import type {
  GetSeriesBody,
  Series,
  Series404Response,
  SeriesId,
  SeriesWithProgressAndRSS,
  UpdateSeriesBody,
} from '../../models';

/**
 * Get a series by ID.
 * @summary Get series
 */
export const getSeries = (id: SeriesId, getSeriesBody?: GetSeriesBody, signal?: AbortSignal) => {
  return customAxios<SeriesWithProgressAndRSS>({
    url: `/api/series/${id}`,
    method: 'GET',
    headers: { 'Content-Type': 'application/json' },
    signal,
  });
};

export const getGetSeriesQueryKey = (id: SeriesId, getSeriesBody?: GetSeriesBody) => {
  return [`/api/series/${id}`, getSeriesBody] as const;
};

export const getGetSeriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getSeries>>,
  TError = Series404Response,
>(
  id: SeriesId,
  getSeriesBody?: GetSeriesBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeries>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSeriesQueryKey(id, getSeriesBody);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSeries>>> = ({ signal }) =>
    getSeries(id, getSeriesBody, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSeries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSeriesQueryResult = NonNullable<Awaited<ReturnType<typeof getSeries>>>;
export type GetSeriesQueryError = Series404Response;

export function useGetSeries<
  TData = Awaited<ReturnType<typeof getSeries>>,
  TError = Series404Response,
>(
  id: SeriesId,
  getSeriesBody: undefined | GetSeriesBody,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeries>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSeries>>,
          TError,
          Awaited<ReturnType<typeof getSeries>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSeries<
  TData = Awaited<ReturnType<typeof getSeries>>,
  TError = Series404Response,
>(
  id: SeriesId,
  getSeriesBody?: GetSeriesBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeries>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSeries>>,
          TError,
          Awaited<ReturnType<typeof getSeries>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSeries<
  TData = Awaited<ReturnType<typeof getSeries>>,
  TError = Series404Response,
>(
  id: SeriesId,
  getSeriesBody?: GetSeriesBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeries>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get series
 */

export function useGetSeries<
  TData = Awaited<ReturnType<typeof getSeries>>,
  TError = Series404Response,
>(
  id: SeriesId,
  getSeriesBody?: GetSeriesBody,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeries>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSeriesQueryOptions(id, getSeriesBody, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update a series by ID.
 * @summary Update series
 */
export const updateSeries = (id: SeriesId, updateSeriesBody: UpdateSeriesBody) => {
  return customAxios<Series>({
    url: `/api/series/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateSeriesBody,
  });
};

export const getUpdateSeriesMutationOptions = <
  TError = Series404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSeries>>,
    TError,
    { id: SeriesId; data: UpdateSeriesBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSeries>>,
  TError,
  { id: SeriesId; data: UpdateSeriesBody },
  TContext
> => {
  const mutationKey = ['updateSeries'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSeries>>,
    { id: SeriesId; data: UpdateSeriesBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateSeries(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateSeriesMutationResult = NonNullable<Awaited<ReturnType<typeof updateSeries>>>;
export type UpdateSeriesMutationBody = UpdateSeriesBody;
export type UpdateSeriesMutationError = Series404Response;

/**
 * @summary Update series
 */
export const useUpdateSeries = <TError = Series404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSeries>>,
      TError,
      { id: SeriesId; data: UpdateSeriesBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateSeries>>,
  TError,
  { id: SeriesId; data: UpdateSeriesBody },
  TContext
> => {
  const mutationOptions = getUpdateSeriesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
