/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../../custom-axios';
import type {
  GetListeningSessions200,
  GetListeningSessionsParams,
  GetListeningStats200,
  LibraryItemId,
  Me404Response,
  MediaProgress,
  MediaProgressPodcastEpisode,
  PodcastId,
  User,
} from '../../models';

/**
 * Get the current user.
 * @summary Get the current user.
 */
export const getMe = (signal?: AbortSignal) => {
  return customAxios<User>({ url: `/api/me`, method: 'GET', signal });
};

export const getGetMeQueryKey = () => {
  return [`/api/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = unknown;

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get the current user.
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get the user's progress for a library item.
 * @summary Get the user's progress for a library item.
 */
export const getProgressLibraryItem = (libraryItemId: LibraryItemId, signal?: AbortSignal) => {
  return customAxios<MediaProgress>({
    url: `/api/me/progress/${libraryItemId}`,
    method: 'GET',
    signal,
  });
};

export const getGetProgressLibraryItemQueryKey = (libraryItemId: LibraryItemId) => {
  return [`/api/me/progress/${libraryItemId}`] as const;
};

export const getGetProgressLibraryItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getProgressLibraryItem>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressLibraryItem>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProgressLibraryItemQueryKey(libraryItemId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgressLibraryItem>>> = ({ signal }) =>
    getProgressLibraryItem(libraryItemId, signal);

  return { queryKey, queryFn, enabled: !!libraryItemId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProgressLibraryItem>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProgressLibraryItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProgressLibraryItem>>
>;
export type GetProgressLibraryItemQueryError = Me404Response;

export function useGetProgressLibraryItem<
  TData = Awaited<ReturnType<typeof getProgressLibraryItem>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressLibraryItem>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgressLibraryItem>>,
          TError,
          Awaited<ReturnType<typeof getProgressLibraryItem>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProgressLibraryItem<
  TData = Awaited<ReturnType<typeof getProgressLibraryItem>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressLibraryItem>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgressLibraryItem>>,
          TError,
          Awaited<ReturnType<typeof getProgressLibraryItem>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProgressLibraryItem<
  TData = Awaited<ReturnType<typeof getProgressLibraryItem>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressLibraryItem>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get the user's progress for a library item.
 */

export function useGetProgressLibraryItem<
  TData = Awaited<ReturnType<typeof getProgressLibraryItem>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressLibraryItem>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetProgressLibraryItemQueryOptions(libraryItemId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get the user's progress for a podcast episode.
 * @summary Get the user's progress for a podcast episode.
 */
export const getProgressPodcastEpisode = (
  libraryItemId: LibraryItemId,
  episodeId: PodcastId,
  signal?: AbortSignal
) => {
  return customAxios<MediaProgressPodcastEpisode>({
    url: `/api/me/progress/${libraryItemId}/${episodeId}`,
    method: 'GET',
    signal,
  });
};

export const getGetProgressPodcastEpisodeQueryKey = (
  libraryItemId: LibraryItemId,
  episodeId: PodcastId
) => {
  return [`/api/me/progress/${libraryItemId}/${episodeId}`] as const;
};

export const getGetProgressPodcastEpisodeQueryOptions = <
  TData = Awaited<ReturnType<typeof getProgressPodcastEpisode>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  episodeId: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressPodcastEpisode>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProgressPodcastEpisodeQueryKey(libraryItemId, episodeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgressPodcastEpisode>>> = ({
    signal,
  }) => getProgressPodcastEpisode(libraryItemId, episodeId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(libraryItemId && episodeId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getProgressPodcastEpisode>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetProgressPodcastEpisodeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProgressPodcastEpisode>>
>;
export type GetProgressPodcastEpisodeQueryError = Me404Response;

export function useGetProgressPodcastEpisode<
  TData = Awaited<ReturnType<typeof getProgressPodcastEpisode>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  episodeId: PodcastId,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressPodcastEpisode>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgressPodcastEpisode>>,
          TError,
          Awaited<ReturnType<typeof getProgressPodcastEpisode>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProgressPodcastEpisode<
  TData = Awaited<ReturnType<typeof getProgressPodcastEpisode>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  episodeId: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressPodcastEpisode>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgressPodcastEpisode>>,
          TError,
          Awaited<ReturnType<typeof getProgressPodcastEpisode>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProgressPodcastEpisode<
  TData = Awaited<ReturnType<typeof getProgressPodcastEpisode>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  episodeId: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressPodcastEpisode>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get the user's progress for a podcast episode.
 */

export function useGetProgressPodcastEpisode<
  TData = Awaited<ReturnType<typeof getProgressPodcastEpisode>>,
  TError = Me404Response,
>(
  libraryItemId: LibraryItemId,
  episodeId: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProgressPodcastEpisode>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetProgressPodcastEpisodeQueryOptions(libraryItemId, episodeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get all listening sessions for the current user.
 * @summary Get all listening sessions for the current user.
 */
export const getListeningSessions = (params: GetListeningSessionsParams, signal?: AbortSignal) => {
  return customAxios<GetListeningSessions200>({
    url: `/api/me/listening-sessions`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetListeningSessionsQueryKey = (params: GetListeningSessionsParams) => {
  return [`/api/me/listening-sessions`, ...(params ? [params] : [])] as const;
};

export const getGetListeningSessionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getListeningSessions>>,
  TError = unknown,
>(
  params: GetListeningSessionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getListeningSessions>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetListeningSessionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListeningSessions>>> = ({ signal }) =>
    getListeningSessions(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListeningSessions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetListeningSessionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListeningSessions>>
>;
export type GetListeningSessionsQueryError = unknown;

export function useGetListeningSessions<
  TData = Awaited<ReturnType<typeof getListeningSessions>>,
  TError = unknown,
>(
  params: GetListeningSessionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getListeningSessions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListeningSessions>>,
          TError,
          Awaited<ReturnType<typeof getListeningSessions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetListeningSessions<
  TData = Awaited<ReturnType<typeof getListeningSessions>>,
  TError = unknown,
>(
  params: GetListeningSessionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getListeningSessions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListeningSessions>>,
          TError,
          Awaited<ReturnType<typeof getListeningSessions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetListeningSessions<
  TData = Awaited<ReturnType<typeof getListeningSessions>>,
  TError = unknown,
>(
  params: GetListeningSessionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getListeningSessions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all listening sessions for the current user.
 */

export function useGetListeningSessions<
  TData = Awaited<ReturnType<typeof getListeningSessions>>,
  TError = unknown,
>(
  params: GetListeningSessionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getListeningSessions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetListeningSessionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get listening stats for the current user.
 * @summary Get listening stats for the current user.
 */
export const getListeningStats = (signal?: AbortSignal) => {
  return customAxios<GetListeningStats200>({
    url: `/api/me/listening-stats`,
    method: 'GET',
    signal,
  });
};

export const getGetListeningStatsQueryKey = () => {
  return [`/api/me/listening-stats`] as const;
};

export const getGetListeningStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getListeningStats>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getListeningStats>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetListeningStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListeningStats>>> = ({ signal }) =>
    getListeningStats(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListeningStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetListeningStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListeningStats>>
>;
export type GetListeningStatsQueryError = unknown;

export function useGetListeningStats<
  TData = Awaited<ReturnType<typeof getListeningStats>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getListeningStats>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListeningStats>>,
          TError,
          Awaited<ReturnType<typeof getListeningStats>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetListeningStats<
  TData = Awaited<ReturnType<typeof getListeningStats>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getListeningStats>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListeningStats>>,
          TError,
          Awaited<ReturnType<typeof getListeningStats>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetListeningStats<
  TData = Awaited<ReturnType<typeof getListeningStats>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getListeningStats>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get listening stats for the current user.
 */

export function useGetListeningStats<
  TData = Awaited<ReturnType<typeof getListeningStats>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getListeningStats>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetListeningStatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
