/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../../custom-axios';
import type {
  GetLibraryItemParams,
  LibraryItem,
  LibraryItem404Response,
  LibraryItemId,
  PlayLibraryItemBody,
  PlayLibraryItemPodcastEpisodeBody,
  PlaybackSessionExpanded,
  PodcastId,
} from '../../models';

/**
 * Get a single library item by ID on server.
 * @summary Get a single library item by ID on server.
 */
export const getLibraryItem = (
  id: LibraryItemId,
  params?: GetLibraryItemParams,
  signal?: AbortSignal
) => {
  return customAxios<LibraryItem>({ url: `/api/items/${id}`, method: 'GET', params, signal });
};

export const getGetLibraryItemQueryKey = (id: LibraryItemId, params?: GetLibraryItemParams) => {
  return [`/api/items/${id}`, ...(params ? [params] : [])] as const;
};

export const getGetLibraryItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getLibraryItem>>,
  TError = LibraryItem404Response,
>(
  id: LibraryItemId,
  params?: GetLibraryItemParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItem>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLibraryItemQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLibraryItem>>> = ({ signal }) =>
    getLibraryItem(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLibraryItem>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLibraryItemQueryResult = NonNullable<Awaited<ReturnType<typeof getLibraryItem>>>;
export type GetLibraryItemQueryError = LibraryItem404Response;

export function useGetLibraryItem<
  TData = Awaited<ReturnType<typeof getLibraryItem>>,
  TError = LibraryItem404Response,
>(
  id: LibraryItemId,
  params: undefined | GetLibraryItemParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItem>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryItem>>,
          TError,
          Awaited<ReturnType<typeof getLibraryItem>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryItem<
  TData = Awaited<ReturnType<typeof getLibraryItem>>,
  TError = LibraryItem404Response,
>(
  id: LibraryItemId,
  params?: GetLibraryItemParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItem>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLibraryItem>>,
          TError,
          Awaited<ReturnType<typeof getLibraryItem>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLibraryItem<
  TData = Awaited<ReturnType<typeof getLibraryItem>>,
  TError = LibraryItem404Response,
>(
  id: LibraryItemId,
  params?: GetLibraryItemParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItem>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a single library item by ID on server.
 */

export function useGetLibraryItem<
  TData = Awaited<ReturnType<typeof getLibraryItem>>,
  TError = LibraryItem404Response,
>(
  id: LibraryItemId,
  params?: GetLibraryItemParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getLibraryItem>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLibraryItemQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Play a library item by ID.
 * @summary Play a library item
 */
export const playLibraryItem = (
  id: LibraryItemId,
  playLibraryItemBody: PlayLibraryItemBody,
  signal?: AbortSignal
) => {
  return customAxios<PlaybackSessionExpanded>({
    url: `/api/items/${id}/play`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: playLibraryItemBody,
    signal,
  });
};

export const getPlayLibraryItemMutationOptions = <
  TError = LibraryItem404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playLibraryItem>>,
    TError,
    { id: LibraryItemId; data: PlayLibraryItemBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof playLibraryItem>>,
  TError,
  { id: LibraryItemId; data: PlayLibraryItemBody },
  TContext
> => {
  const mutationKey = ['playLibraryItem'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof playLibraryItem>>,
    { id: LibraryItemId; data: PlayLibraryItemBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return playLibraryItem(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlayLibraryItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof playLibraryItem>>
>;
export type PlayLibraryItemMutationBody = PlayLibraryItemBody;
export type PlayLibraryItemMutationError = LibraryItem404Response;

/**
 * @summary Play a library item
 */
export const usePlayLibraryItem = <TError = LibraryItem404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playLibraryItem>>,
      TError,
      { id: LibraryItemId; data: PlayLibraryItemBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof playLibraryItem>>,
  TError,
  { id: LibraryItemId; data: PlayLibraryItemBody },
  TContext
> => {
  const mutationOptions = getPlayLibraryItemMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Play a podcast by library item ID and episode ID.
 * @summary Play a podcast episode
 */
export const playLibraryItemPodcastEpisode = (
  id: LibraryItemId,
  episodeId: PodcastId,
  playLibraryItemPodcastEpisodeBody: PlayLibraryItemPodcastEpisodeBody,
  signal?: AbortSignal
) => {
  return customAxios<PlaybackSessionExpanded>({
    url: `/api/items/${id}/play/${episodeId}`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: playLibraryItemPodcastEpisodeBody,
    signal,
  });
};

export const getPlayLibraryItemPodcastEpisodeMutationOptions = <
  TError = LibraryItem404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playLibraryItemPodcastEpisode>>,
    TError,
    { id: LibraryItemId; episodeId: PodcastId; data: PlayLibraryItemPodcastEpisodeBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof playLibraryItemPodcastEpisode>>,
  TError,
  { id: LibraryItemId; episodeId: PodcastId; data: PlayLibraryItemPodcastEpisodeBody },
  TContext
> => {
  const mutationKey = ['playLibraryItemPodcastEpisode'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof playLibraryItemPodcastEpisode>>,
    { id: LibraryItemId; episodeId: PodcastId; data: PlayLibraryItemPodcastEpisodeBody }
  > = (props) => {
    const { id, episodeId, data } = props ?? {};

    return playLibraryItemPodcastEpisode(id, episodeId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlayLibraryItemPodcastEpisodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof playLibraryItemPodcastEpisode>>
>;
export type PlayLibraryItemPodcastEpisodeMutationBody = PlayLibraryItemPodcastEpisodeBody;
export type PlayLibraryItemPodcastEpisodeMutationError = LibraryItem404Response;

/**
 * @summary Play a podcast episode
 */
export const usePlayLibraryItemPodcastEpisode = <
  TError = LibraryItem404Response,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playLibraryItemPodcastEpisode>>,
      TError,
      { id: LibraryItemId; episodeId: PodcastId; data: PlayLibraryItemPodcastEpisodeBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof playLibraryItemPodcastEpisode>>,
  TError,
  { id: LibraryItemId; episodeId: PodcastId; data: PlayLibraryItemPodcastEpisodeBody },
  TContext
> => {
  const mutationOptions = getPlayLibraryItemPodcastEpisodeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
