/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../../custom-axios';
import type {
  ConfigureNotificationSettingsBody,
  CreateNotification200,
  CreateNotificationBody,
  DeleteNotification200,
  GetNotificationEventData200,
  GetNotifications200,
  Notification200Response,
  Notification404Response,
  NotificationId,
  SendDefaultTestNotificationParams,
  UpdateNotification200,
  UpdateNotificationBody,
} from '../../models';

/**
 * Get all Apprise notification events and notification settings for server.
 * @summary Get notification settings
 */
export const getNotifications = (signal?: AbortSignal) => {
  return customAxios<GetNotifications200>({ url: `/api/notifications`, method: 'GET', signal });
};

export const getGetNotificationsQueryKey = () => {
  return [`/api/notifications`] as const;
};

export const getGetNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = Notification404Response,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNotificationsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotifications>>> = ({ signal }) =>
    getNotifications(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNotifications>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof getNotifications>>>;
export type GetNotificationsQueryError = Notification404Response;

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = Notification404Response,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = Notification404Response,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = Notification404Response,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get notification settings
 */

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = Notification404Response,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNotificationsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update the URL, max failed attempts, and maximum notifications that can be queued for Apprise.
 * @summary Update select notification settings
 */
export const configureNotificationSettings = (
  configureNotificationSettingsBody: ConfigureNotificationSettingsBody
) => {
  return customAxios<Notification200Response>({
    url: `/api/notifications`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: configureNotificationSettingsBody,
  });
};

export const getConfigureNotificationSettingsMutationOptions = <
  TError = Notification404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof configureNotificationSettings>>,
    TError,
    { data: ConfigureNotificationSettingsBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof configureNotificationSettings>>,
  TError,
  { data: ConfigureNotificationSettingsBody },
  TContext
> => {
  const mutationKey = ['configureNotificationSettings'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof configureNotificationSettings>>,
    { data: ConfigureNotificationSettingsBody }
  > = (props) => {
    const { data } = props ?? {};

    return configureNotificationSettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConfigureNotificationSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof configureNotificationSettings>>
>;
export type ConfigureNotificationSettingsMutationBody = ConfigureNotificationSettingsBody;
export type ConfigureNotificationSettingsMutationError = Notification404Response;

/**
 * @summary Update select notification settings
 */
export const useConfigureNotificationSettings = <
  TError = Notification404Response,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof configureNotificationSettings>>,
      TError,
      { data: ConfigureNotificationSettingsBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof configureNotificationSettings>>,
  TError,
  { data: ConfigureNotificationSettingsBody },
  TContext
> => {
  const mutationOptions = getConfigureNotificationSettingsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Create or update Notification settings.
 * @summary Create notification settings
 */
export const createNotification = (
  createNotificationBody: CreateNotificationBody,
  signal?: AbortSignal
) => {
  return customAxios<CreateNotification200>({
    url: `/api/notifications`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createNotificationBody,
    signal,
  });
};

export const getCreateNotificationMutationOptions = <
  TError = Notification404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createNotification>>,
    TError,
    { data: CreateNotificationBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createNotification>>,
  TError,
  { data: CreateNotificationBody },
  TContext
> => {
  const mutationKey = ['createNotification'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createNotification>>,
    { data: CreateNotificationBody }
  > = (props) => {
    const { data } = props ?? {};

    return createNotification(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateNotificationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createNotification>>
>;
export type CreateNotificationMutationBody = CreateNotificationBody;
export type CreateNotificationMutationError = Notification404Response;

/**
 * @summary Create notification settings
 */
export const useCreateNotification = <TError = Notification404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createNotification>>,
      TError,
      { data: CreateNotificationBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createNotification>>,
  TError,
  { data: CreateNotificationBody },
  TContext
> => {
  const mutationOptions = getCreateNotificationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get all Apprise notification event data for the server.
 * @summary Get notification event data
 */
export const getNotificationEventData = (signal?: AbortSignal) => {
  return customAxios<GetNotificationEventData200>({
    url: `/api/notificationdata`,
    method: 'GET',
    signal,
  });
};

export const getGetNotificationEventDataQueryKey = () => {
  return [`/api/notificationdata`] as const;
};

export const getGetNotificationEventDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getNotificationEventData>>,
  TError = Notification404Response,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getNotificationEventData>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNotificationEventDataQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationEventData>>> = ({
    signal,
  }) => getNotificationEventData(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNotificationEventData>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNotificationEventDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNotificationEventData>>
>;
export type GetNotificationEventDataQueryError = Notification404Response;

export function useGetNotificationEventData<
  TData = Awaited<ReturnType<typeof getNotificationEventData>>,
  TError = Notification404Response,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotificationEventData>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationEventData>>,
          TError,
          Awaited<ReturnType<typeof getNotificationEventData>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotificationEventData<
  TData = Awaited<ReturnType<typeof getNotificationEventData>>,
  TError = Notification404Response,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotificationEventData>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationEventData>>,
          TError,
          Awaited<ReturnType<typeof getNotificationEventData>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotificationEventData<
  TData = Awaited<ReturnType<typeof getNotificationEventData>>,
  TError = Notification404Response,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotificationEventData>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get notification event data
 */

export function useGetNotificationEventData<
  TData = Awaited<ReturnType<typeof getNotificationEventData>>,
  TError = Notification404Response,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotificationEventData>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNotificationEventDataQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Send a test notification.
 * @summary Send general test notification
 */
export const sendDefaultTestNotification = (
  params?: SendDefaultTestNotificationParams,
  signal?: AbortSignal
) => {
  return customAxios<Notification200Response>({
    url: `/api/notifications/test`,
    method: 'GET',
    params,
    signal,
  });
};

export const getSendDefaultTestNotificationQueryKey = (
  params?: SendDefaultTestNotificationParams
) => {
  return [`/api/notifications/test`, ...(params ? [params] : [])] as const;
};

export const getSendDefaultTestNotificationQueryOptions = <
  TData = Awaited<ReturnType<typeof sendDefaultTestNotification>>,
  TError = Notification404Response,
>(
  params?: SendDefaultTestNotificationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendDefaultTestNotification>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSendDefaultTestNotificationQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sendDefaultTestNotification>>> = ({
    signal,
  }) => sendDefaultTestNotification(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sendDefaultTestNotification>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SendDefaultTestNotificationQueryResult = NonNullable<
  Awaited<ReturnType<typeof sendDefaultTestNotification>>
>;
export type SendDefaultTestNotificationQueryError = Notification404Response;

export function useSendDefaultTestNotification<
  TData = Awaited<ReturnType<typeof sendDefaultTestNotification>>,
  TError = Notification404Response,
>(
  params: undefined | SendDefaultTestNotificationParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendDefaultTestNotification>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sendDefaultTestNotification>>,
          TError,
          Awaited<ReturnType<typeof sendDefaultTestNotification>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSendDefaultTestNotification<
  TData = Awaited<ReturnType<typeof sendDefaultTestNotification>>,
  TError = Notification404Response,
>(
  params?: SendDefaultTestNotificationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendDefaultTestNotification>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sendDefaultTestNotification>>,
          TError,
          Awaited<ReturnType<typeof sendDefaultTestNotification>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSendDefaultTestNotification<
  TData = Awaited<ReturnType<typeof sendDefaultTestNotification>>,
  TError = Notification404Response,
>(
  params?: SendDefaultTestNotificationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendDefaultTestNotification>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Send general test notification
 */

export function useSendDefaultTestNotification<
  TData = Awaited<ReturnType<typeof sendDefaultTestNotification>>,
  TError = Notification404Response,
>(
  params?: SendDefaultTestNotificationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendDefaultTestNotification>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSendDefaultTestNotificationQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Delete the notification by ID and return the notification settings.
 * @summary Delete a notification
 */
export const deleteNotification = (id: NotificationId) => {
  return customAxios<DeleteNotification200>({ url: `/api/notifications/${id}`, method: 'DELETE' });
};

export const getDeleteNotificationMutationOptions = <
  TError = Notification404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteNotification>>,
    TError,
    { id: NotificationId },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteNotification>>,
  TError,
  { id: NotificationId },
  TContext
> => {
  const mutationKey = ['deleteNotification'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteNotification>>,
    { id: NotificationId }
  > = (props) => {
    const { id } = props ?? {};

    return deleteNotification(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteNotificationMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteNotification>>
>;

export type DeleteNotificationMutationError = Notification404Response;

/**
 * @summary Delete a notification
 */
export const useDeleteNotification = <TError = Notification404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteNotification>>,
      TError,
      { id: NotificationId },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteNotification>>,
  TError,
  { id: NotificationId },
  TContext
> => {
  const mutationOptions = getDeleteNotificationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Update an individual Notification by ID
 * @summary Update a notification
 */
export const updateNotification = (
  id: NotificationId,
  updateNotificationBody: UpdateNotificationBody
) => {
  return customAxios<UpdateNotification200>({
    url: `/api/notifications/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateNotificationBody,
  });
};

export const getUpdateNotificationMutationOptions = <
  TError = Notification404Response,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateNotification>>,
    TError,
    { id: NotificationId; data: UpdateNotificationBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateNotification>>,
  TError,
  { id: NotificationId; data: UpdateNotificationBody },
  TContext
> => {
  const mutationKey = ['updateNotification'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateNotification>>,
    { id: NotificationId; data: UpdateNotificationBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateNotification(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateNotificationMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateNotification>>
>;
export type UpdateNotificationMutationBody = UpdateNotificationBody;
export type UpdateNotificationMutationError = Notification404Response;

/**
 * @summary Update a notification
 */
export const useUpdateNotification = <TError = Notification404Response, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateNotification>>,
      TError,
      { id: NotificationId; data: UpdateNotificationBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateNotification>>,
  TError,
  { id: NotificationId; data: UpdateNotificationBody },
  TContext
> => {
  const mutationOptions = getUpdateNotificationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Send a test to the given notification by ID.
 * @summary Send a test notification
 */
export const sendTestNotification = (id: NotificationId, signal?: AbortSignal) => {
  return customAxios<Notification200Response>({
    url: `/api/notifications/${id}/test`,
    method: 'GET',
    signal,
  });
};

export const getSendTestNotificationQueryKey = (id: NotificationId) => {
  return [`/api/notifications/${id}/test`] as const;
};

export const getSendTestNotificationQueryOptions = <
  TData = Awaited<ReturnType<typeof sendTestNotification>>,
  TError = Notification404Response,
>(
  id: NotificationId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendTestNotification>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSendTestNotificationQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sendTestNotification>>> = ({ signal }) =>
    sendTestNotification(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sendTestNotification>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SendTestNotificationQueryResult = NonNullable<
  Awaited<ReturnType<typeof sendTestNotification>>
>;
export type SendTestNotificationQueryError = Notification404Response;

export function useSendTestNotification<
  TData = Awaited<ReturnType<typeof sendTestNotification>>,
  TError = Notification404Response,
>(
  id: NotificationId,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendTestNotification>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sendTestNotification>>,
          TError,
          Awaited<ReturnType<typeof sendTestNotification>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSendTestNotification<
  TData = Awaited<ReturnType<typeof sendTestNotification>>,
  TError = Notification404Response,
>(
  id: NotificationId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendTestNotification>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sendTestNotification>>,
          TError,
          Awaited<ReturnType<typeof sendTestNotification>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSendTestNotification<
  TData = Awaited<ReturnType<typeof sendTestNotification>>,
  TError = Notification404Response,
>(
  id: NotificationId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendTestNotification>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Send a test notification
 */

export function useSendTestNotification<
  TData = Awaited<ReturnType<typeof sendTestNotification>>,
  TError = Notification404Response,
>(
  id: NotificationId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sendTestNotification>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSendTestNotificationQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
