/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../../custom-axios';
import type {
  Email200Response,
  EmailSettings,
  Ereader200Response,
  SendEBookToDeviceBody,
  UpdateEReaderDevicesBody,
} from '../../models';

/**
 * Get email settings for sending e-books to e-readers.
 * @summary Get email settings
 */
export const getEmailSettings = (signal?: AbortSignal) => {
  return customAxios<Email200Response>({ url: `/api/emails/settings`, method: 'GET', signal });
};

export const getGetEmailSettingsQueryKey = () => {
  return [`/api/emails/settings`] as const;
};

export const getGetEmailSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getEmailSettings>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmailSettings>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEmailSettingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEmailSettings>>> = ({ signal }) =>
    getEmailSettings(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEmailSettings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEmailSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getEmailSettings>>>;
export type GetEmailSettingsQueryError = unknown;

export function useGetEmailSettings<
  TData = Awaited<ReturnType<typeof getEmailSettings>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmailSettings>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmailSettings>>,
          TError,
          Awaited<ReturnType<typeof getEmailSettings>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEmailSettings<
  TData = Awaited<ReturnType<typeof getEmailSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmailSettings>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmailSettings>>,
          TError,
          Awaited<ReturnType<typeof getEmailSettings>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEmailSettings<
  TData = Awaited<ReturnType<typeof getEmailSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmailSettings>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get email settings
 */

export function useGetEmailSettings<
  TData = Awaited<ReturnType<typeof getEmailSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmailSettings>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetEmailSettingsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update email settings
 */
export const updateEmailSettings = (emailSettings: EmailSettings) => {
  return customAxios<Email200Response>({
    url: `/api/emails/settings`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: emailSettings,
  });
};

export const getUpdateEmailSettingsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateEmailSettings>>,
    TError,
    { data: EmailSettings },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateEmailSettings>>,
  TError,
  { data: EmailSettings },
  TContext
> => {
  const mutationKey = ['updateEmailSettings'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateEmailSettings>>,
    { data: EmailSettings }
  > = (props) => {
    const { data } = props ?? {};

    return updateEmailSettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateEmailSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateEmailSettings>>
>;
export type UpdateEmailSettingsMutationBody = EmailSettings;
export type UpdateEmailSettingsMutationError = unknown;

/**
 * @summary Update email settings
 */
export const useUpdateEmailSettings = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateEmailSettings>>,
      TError,
      { data: EmailSettings },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateEmailSettings>>,
  TError,
  { data: EmailSettings },
  TContext
> => {
  const mutationOptions = getUpdateEmailSettingsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Send test email
 */
export const sendTestEmail = (signal?: AbortSignal) => {
  return customAxios<void>({ url: `/api/emails/test`, method: 'POST', signal });
};

export const getSendTestEmailMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof sendTestEmail>>, TError, void, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof sendTestEmail>>, TError, void, TContext> => {
  const mutationKey = ['sendTestEmail'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendTestEmail>>, void> = () => {
    return sendTestEmail();
  };

  return { mutationFn, ...mutationOptions };
};

export type SendTestEmailMutationResult = NonNullable<Awaited<ReturnType<typeof sendTestEmail>>>;

export type SendTestEmailMutationError = unknown;

/**
 * @summary Send test email
 */
export const useSendTestEmail = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sendTestEmail>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof sendTestEmail>>, TError, void, TContext> => {
  const mutationOptions = getSendTestEmailMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update e-reader devices
 */
export const updateEReaderDevices = (
  updateEReaderDevicesBody: UpdateEReaderDevicesBody,
  signal?: AbortSignal
) => {
  return customAxios<Ereader200Response>({
    url: `/api/emails/ereader-devices`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: updateEReaderDevicesBody,
    signal,
  });
};

export const getUpdateEReaderDevicesMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateEReaderDevices>>,
    TError,
    { data: UpdateEReaderDevicesBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateEReaderDevices>>,
  TError,
  { data: UpdateEReaderDevicesBody },
  TContext
> => {
  const mutationKey = ['updateEReaderDevices'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateEReaderDevices>>,
    { data: UpdateEReaderDevicesBody }
  > = (props) => {
    const { data } = props ?? {};

    return updateEReaderDevices(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateEReaderDevicesMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateEReaderDevices>>
>;
export type UpdateEReaderDevicesMutationBody = UpdateEReaderDevicesBody;
export type UpdateEReaderDevicesMutationError = void;

/**
 * @summary Update e-reader devices
 */
export const useUpdateEReaderDevices = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateEReaderDevices>>,
      TError,
      { data: UpdateEReaderDevicesBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateEReaderDevices>>,
  TError,
  { data: UpdateEReaderDevicesBody },
  TContext
> => {
  const mutationOptions = getUpdateEReaderDevicesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Send ebook to device
 */
export const sendEBookToDevice = (
  sendEBookToDeviceBody: SendEBookToDeviceBody,
  signal?: AbortSignal
) => {
  return customAxios<void>({
    url: `/api/emails/send-ebook-to-device`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sendEBookToDeviceBody,
    signal,
  });
};

export const getSendEBookToDeviceMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendEBookToDevice>>,
    TError,
    { data: SendEBookToDeviceBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendEBookToDevice>>,
  TError,
  { data: SendEBookToDeviceBody },
  TContext
> => {
  const mutationKey = ['sendEBookToDevice'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendEBookToDevice>>,
    { data: SendEBookToDeviceBody }
  > = (props) => {
    const { data } = props ?? {};

    return sendEBookToDevice(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendEBookToDeviceMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendEBookToDevice>>
>;
export type SendEBookToDeviceMutationBody = SendEBookToDeviceBody;
export type SendEBookToDeviceMutationError = void;

/**
 * @summary Send ebook to device
 */
export const useSendEBookToDevice = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sendEBookToDevice>>,
      TError,
      { data: SendEBookToDeviceBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof sendEBookToDevice>>,
  TError,
  { data: SendEBookToDeviceBody },
  TContext
> => {
  const mutationOptions = getSendEBookToDeviceMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
