/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxios } from '../../custom-axios';
import type {
  BulkCreatePodcastsFromOpmlFeedUrlsBody,
  CheckNewEpisodes200,
  CheckNewEpisodesParams,
  FindEpisode200,
  FindEpisodeParams,
  GetEpisodeDownloads200,
  GetFeedsFromOPMLText200,
  GetFeedsFromOPMLTextBody,
  GetPodcastFeed200,
  GetPodcastFeedBody,
  Podcast,
  PodcastEpisode,
  PodcastId,
  QuickMatchEpisodes200,
  QuickMatchEpisodesParams,
  RemoveEpisodeParams,
  UpdateEpisodeBody,
} from '../../models';

/**
 * @summary Create a new podcast
 */
export const createPodcast = (podcast: Podcast, signal?: AbortSignal) => {
  return customAxios<Podcast>({
    url: `/api/podcasts`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: podcast,
    signal,
  });
};

export const getCreatePodcastMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPodcast>>,
    TError,
    { data: Podcast },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPodcast>>,
  TError,
  { data: Podcast },
  TContext
> => {
  const mutationKey = ['createPodcast'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPodcast>>,
    { data: Podcast }
  > = (props) => {
    const { data } = props ?? {};

    return createPodcast(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePodcastMutationResult = NonNullable<Awaited<ReturnType<typeof createPodcast>>>;
export type CreatePodcastMutationBody = Podcast;
export type CreatePodcastMutationError = void;

/**
 * @summary Create a new podcast
 */
export const useCreatePodcast = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPodcast>>,
      TError,
      { data: Podcast },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createPodcast>>,
  TError,
  { data: Podcast },
  TContext
> => {
  const mutationOptions = getCreatePodcastMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get podcast feed
 */
export const getPodcastFeed = (getPodcastFeedBody: GetPodcastFeedBody, signal?: AbortSignal) => {
  return customAxios<GetPodcastFeed200>({
    url: `/api/podcasts/feed`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: getPodcastFeedBody,
    signal,
  });
};

export const getGetPodcastFeedMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getPodcastFeed>>,
    TError,
    { data: GetPodcastFeedBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getPodcastFeed>>,
  TError,
  { data: GetPodcastFeedBody },
  TContext
> => {
  const mutationKey = ['getPodcastFeed'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getPodcastFeed>>,
    { data: GetPodcastFeedBody }
  > = (props) => {
    const { data } = props ?? {};

    return getPodcastFeed(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetPodcastFeedMutationResult = NonNullable<Awaited<ReturnType<typeof getPodcastFeed>>>;
export type GetPodcastFeedMutationBody = GetPodcastFeedBody;
export type GetPodcastFeedMutationError = void;

/**
 * @summary Get podcast feed
 */
export const useGetPodcastFeed = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getPodcastFeed>>,
      TError,
      { data: GetPodcastFeedBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof getPodcastFeed>>,
  TError,
  { data: GetPodcastFeedBody },
  TContext
> => {
  const mutationOptions = getGetPodcastFeedMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Parse OPML text and return an array of feeds
 * @summary Get feeds from OPML text
 */
export const getFeedsFromOPMLText = (
  getFeedsFromOPMLTextBody: GetFeedsFromOPMLTextBody,
  signal?: AbortSignal
) => {
  return customAxios<GetFeedsFromOPMLText200>({
    url: `/api/podcasts/opml/parse`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: getFeedsFromOPMLTextBody,
    signal,
  });
};

export const getGetFeedsFromOPMLTextMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getFeedsFromOPMLText>>,
    TError,
    { data: GetFeedsFromOPMLTextBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getFeedsFromOPMLText>>,
  TError,
  { data: GetFeedsFromOPMLTextBody },
  TContext
> => {
  const mutationKey = ['getFeedsFromOPMLText'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getFeedsFromOPMLText>>,
    { data: GetFeedsFromOPMLTextBody }
  > = (props) => {
    const { data } = props ?? {};

    return getFeedsFromOPMLText(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetFeedsFromOPMLTextMutationResult = NonNullable<
  Awaited<ReturnType<typeof getFeedsFromOPMLText>>
>;
export type GetFeedsFromOPMLTextMutationBody = GetFeedsFromOPMLTextBody;
export type GetFeedsFromOPMLTextMutationError = void;

/**
 * @summary Get feeds from OPML text
 */
export const useGetFeedsFromOPMLText = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getFeedsFromOPMLText>>,
      TError,
      { data: GetFeedsFromOPMLTextBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof getFeedsFromOPMLText>>,
  TError,
  { data: GetFeedsFromOPMLTextBody },
  TContext
> => {
  const mutationOptions = getGetFeedsFromOPMLTextMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Bulk create podcasts from OPML feed URLs
 */
export const bulkCreatePodcastsFromOpmlFeedUrls = (
  bulkCreatePodcastsFromOpmlFeedUrlsBody: BulkCreatePodcastsFromOpmlFeedUrlsBody,
  signal?: AbortSignal
) => {
  return customAxios<void>({
    url: `/api/podcasts/opml/create`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: bulkCreatePodcastsFromOpmlFeedUrlsBody,
    signal,
  });
};

export const getBulkCreatePodcastsFromOpmlFeedUrlsMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bulkCreatePodcastsFromOpmlFeedUrls>>,
    TError,
    { data: BulkCreatePodcastsFromOpmlFeedUrlsBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof bulkCreatePodcastsFromOpmlFeedUrls>>,
  TError,
  { data: BulkCreatePodcastsFromOpmlFeedUrlsBody },
  TContext
> => {
  const mutationKey = ['bulkCreatePodcastsFromOpmlFeedUrls'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bulkCreatePodcastsFromOpmlFeedUrls>>,
    { data: BulkCreatePodcastsFromOpmlFeedUrlsBody }
  > = (props) => {
    const { data } = props ?? {};

    return bulkCreatePodcastsFromOpmlFeedUrls(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BulkCreatePodcastsFromOpmlFeedUrlsMutationResult = NonNullable<
  Awaited<ReturnType<typeof bulkCreatePodcastsFromOpmlFeedUrls>>
>;
export type BulkCreatePodcastsFromOpmlFeedUrlsMutationBody = BulkCreatePodcastsFromOpmlFeedUrlsBody;
export type BulkCreatePodcastsFromOpmlFeedUrlsMutationError = void;

/**
 * @summary Bulk create podcasts from OPML feed URLs
 */
export const useBulkCreatePodcastsFromOpmlFeedUrls = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof bulkCreatePodcastsFromOpmlFeedUrls>>,
      TError,
      { data: BulkCreatePodcastsFromOpmlFeedUrlsBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof bulkCreatePodcastsFromOpmlFeedUrls>>,
  TError,
  { data: BulkCreatePodcastsFromOpmlFeedUrlsBody },
  TContext
> => {
  const mutationOptions = getBulkCreatePodcastsFromOpmlFeedUrlsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Check and download new episodes
 */
export const checkNewEpisodes = (
  id: PodcastId,
  params?: CheckNewEpisodesParams,
  signal?: AbortSignal
) => {
  return customAxios<CheckNewEpisodes200>({
    url: `/api/podcasts/${id}/checknew`,
    method: 'GET',
    params,
    signal,
  });
};

export const getCheckNewEpisodesQueryKey = (id: PodcastId, params?: CheckNewEpisodesParams) => {
  return [`/api/podcasts/${id}/checknew`, ...(params ? [params] : [])] as const;
};

export const getCheckNewEpisodesQueryOptions = <
  TData = Awaited<ReturnType<typeof checkNewEpisodes>>,
  TError = void,
>(
  id: PodcastId,
  params?: CheckNewEpisodesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNewEpisodes>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCheckNewEpisodesQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof checkNewEpisodes>>> = ({ signal }) =>
    checkNewEpisodes(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof checkNewEpisodes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CheckNewEpisodesQueryResult = NonNullable<Awaited<ReturnType<typeof checkNewEpisodes>>>;
export type CheckNewEpisodesQueryError = void;

export function useCheckNewEpisodes<
  TData = Awaited<ReturnType<typeof checkNewEpisodes>>,
  TError = void,
>(
  id: PodcastId,
  params: undefined | CheckNewEpisodesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNewEpisodes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkNewEpisodes>>,
          TError,
          Awaited<ReturnType<typeof checkNewEpisodes>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCheckNewEpisodes<
  TData = Awaited<ReturnType<typeof checkNewEpisodes>>,
  TError = void,
>(
  id: PodcastId,
  params?: CheckNewEpisodesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNewEpisodes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkNewEpisodes>>,
          TError,
          Awaited<ReturnType<typeof checkNewEpisodes>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCheckNewEpisodes<
  TData = Awaited<ReturnType<typeof checkNewEpisodes>>,
  TError = void,
>(
  id: PodcastId,
  params?: CheckNewEpisodesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNewEpisodes>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Check and download new episodes
 */

export function useCheckNewEpisodes<
  TData = Awaited<ReturnType<typeof checkNewEpisodes>>,
  TError = void,
>(
  id: PodcastId,
  params?: CheckNewEpisodesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof checkNewEpisodes>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCheckNewEpisodesQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Clear episode download queue
 */
export const clearEpisodeDownloadQueue = (id: PodcastId, signal?: AbortSignal) => {
  return customAxios<void>({ url: `/api/podcasts/${id}/clear-queue`, method: 'GET', signal });
};

export const getClearEpisodeDownloadQueueQueryKey = (id: PodcastId) => {
  return [`/api/podcasts/${id}/clear-queue`] as const;
};

export const getClearEpisodeDownloadQueueQueryOptions = <
  TData = Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>,
  TError = void,
>(
  id: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getClearEpisodeDownloadQueueQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>> = ({
    signal,
  }) => clearEpisodeDownloadQueue(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ClearEpisodeDownloadQueueQueryResult = NonNullable<
  Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>
>;
export type ClearEpisodeDownloadQueueQueryError = void;

export function useClearEpisodeDownloadQueue<
  TData = Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>,
  TError = void,
>(
  id: PodcastId,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>,
          TError,
          Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClearEpisodeDownloadQueue<
  TData = Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>,
  TError = void,
>(
  id: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>,
          TError,
          Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClearEpisodeDownloadQueue<
  TData = Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>,
  TError = void,
>(
  id: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Clear episode download queue
 */

export function useClearEpisodeDownloadQueue<
  TData = Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>,
  TError = void,
>(
  id: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof clearEpisodeDownloadQueue>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getClearEpisodeDownloadQueueQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get episode downloads
 */
export const getEpisodeDownloads = (id: PodcastId, signal?: AbortSignal) => {
  return customAxios<GetEpisodeDownloads200>({
    url: `/api/podcasts/${id}/downloads`,
    method: 'GET',
    signal,
  });
};

export const getGetEpisodeDownloadsQueryKey = (id: PodcastId) => {
  return [`/api/podcasts/${id}/downloads`] as const;
};

export const getGetEpisodeDownloadsQueryOptions = <
  TData = Awaited<ReturnType<typeof getEpisodeDownloads>>,
  TError = void,
>(
  id: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEpisodeDownloads>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEpisodeDownloadsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEpisodeDownloads>>> = ({ signal }) =>
    getEpisodeDownloads(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEpisodeDownloads>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEpisodeDownloadsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEpisodeDownloads>>
>;
export type GetEpisodeDownloadsQueryError = void;

export function useGetEpisodeDownloads<
  TData = Awaited<ReturnType<typeof getEpisodeDownloads>>,
  TError = void,
>(
  id: PodcastId,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEpisodeDownloads>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEpisodeDownloads>>,
          TError,
          Awaited<ReturnType<typeof getEpisodeDownloads>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEpisodeDownloads<
  TData = Awaited<ReturnType<typeof getEpisodeDownloads>>,
  TError = void,
>(
  id: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEpisodeDownloads>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEpisodeDownloads>>,
          TError,
          Awaited<ReturnType<typeof getEpisodeDownloads>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEpisodeDownloads<
  TData = Awaited<ReturnType<typeof getEpisodeDownloads>>,
  TError = void,
>(
  id: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEpisodeDownloads>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get episode downloads
 */

export function useGetEpisodeDownloads<
  TData = Awaited<ReturnType<typeof getEpisodeDownloads>>,
  TError = void,
>(
  id: PodcastId,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEpisodeDownloads>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetEpisodeDownloadsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Find episode by title
 */
export const findEpisode = (id: PodcastId, params: FindEpisodeParams, signal?: AbortSignal) => {
  return customAxios<FindEpisode200>({
    url: `/api/podcasts/${id}/search-episode`,
    method: 'GET',
    params,
    signal,
  });
};

export const getFindEpisodeQueryKey = (id: PodcastId, params: FindEpisodeParams) => {
  return [`/api/podcasts/${id}/search-episode`, ...(params ? [params] : [])] as const;
};

export const getFindEpisodeQueryOptions = <
  TData = Awaited<ReturnType<typeof findEpisode>>,
  TError = void,
>(
  id: PodcastId,
  params: FindEpisodeParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findEpisode>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindEpisodeQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findEpisode>>> = ({ signal }) =>
    findEpisode(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findEpisode>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindEpisodeQueryResult = NonNullable<Awaited<ReturnType<typeof findEpisode>>>;
export type FindEpisodeQueryError = void;

export function useFindEpisode<TData = Awaited<ReturnType<typeof findEpisode>>, TError = void>(
  id: PodcastId,
  params: FindEpisodeParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findEpisode>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findEpisode>>,
          TError,
          Awaited<ReturnType<typeof findEpisode>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindEpisode<TData = Awaited<ReturnType<typeof findEpisode>>, TError = void>(
  id: PodcastId,
  params: FindEpisodeParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findEpisode>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findEpisode>>,
          TError,
          Awaited<ReturnType<typeof findEpisode>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindEpisode<TData = Awaited<ReturnType<typeof findEpisode>>, TError = void>(
  id: PodcastId,
  params: FindEpisodeParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findEpisode>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find episode by title
 */

export function useFindEpisode<TData = Awaited<ReturnType<typeof findEpisode>>, TError = void>(
  id: PodcastId,
  params: FindEpisodeParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findEpisode>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindEpisodeQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Download podcast episodes
 */
export const downloadEpisodes = (
  id: PodcastId,
  downloadEpisodesBody: string[],
  signal?: AbortSignal
) => {
  return customAxios<void>({
    url: `/api/podcasts/${id}/download-episodes`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: downloadEpisodesBody,
    signal,
  });
};

export const getDownloadEpisodesMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof downloadEpisodes>>,
    TError,
    { id: PodcastId; data: string[] },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof downloadEpisodes>>,
  TError,
  { id: PodcastId; data: string[] },
  TContext
> => {
  const mutationKey = ['downloadEpisodes'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof downloadEpisodes>>,
    { id: PodcastId; data: string[] }
  > = (props) => {
    const { id, data } = props ?? {};

    return downloadEpisodes(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DownloadEpisodesMutationResult = NonNullable<
  Awaited<ReturnType<typeof downloadEpisodes>>
>;
export type DownloadEpisodesMutationBody = string[];
export type DownloadEpisodesMutationError = void;

/**
 * @summary Download podcast episodes
 */
export const useDownloadEpisodes = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof downloadEpisodes>>,
      TError,
      { id: PodcastId; data: string[] },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof downloadEpisodes>>,
  TError,
  { id: PodcastId; data: string[] },
  TContext
> => {
  const mutationOptions = getDownloadEpisodesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Quick match podcast episodes
 */
export const quickMatchEpisodes = (
  id: PodcastId,
  params?: QuickMatchEpisodesParams,
  signal?: AbortSignal
) => {
  return customAxios<QuickMatchEpisodes200>({
    url: `/api/podcasts/${id}/match-episodes`,
    method: 'POST',
    params,
    signal,
  });
};

export const getQuickMatchEpisodesMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof quickMatchEpisodes>>,
    TError,
    { id: PodcastId; params?: QuickMatchEpisodesParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof quickMatchEpisodes>>,
  TError,
  { id: PodcastId; params?: QuickMatchEpisodesParams },
  TContext
> => {
  const mutationKey = ['quickMatchEpisodes'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof quickMatchEpisodes>>,
    { id: PodcastId; params?: QuickMatchEpisodesParams }
  > = (props) => {
    const { id, params } = props ?? {};

    return quickMatchEpisodes(id, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuickMatchEpisodesMutationResult = NonNullable<
  Awaited<ReturnType<typeof quickMatchEpisodes>>
>;

export type QuickMatchEpisodesMutationError = void;

/**
 * @summary Quick match podcast episodes
 */
export const useQuickMatchEpisodes = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof quickMatchEpisodes>>,
      TError,
      { id: PodcastId; params?: QuickMatchEpisodesParams },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof quickMatchEpisodes>>,
  TError,
  { id: PodcastId; params?: QuickMatchEpisodesParams },
  TContext
> => {
  const mutationOptions = getQuickMatchEpisodesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update a podcast episode
 */
export const updateEpisode = (
  id: PodcastId,
  episodeId: PodcastId,
  updateEpisodeBody: UpdateEpisodeBody
) => {
  return customAxios<Podcast>({
    url: `/api/podcasts/${id}/episode/${episodeId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateEpisodeBody,
  });
};

export const getUpdateEpisodeMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateEpisode>>,
    TError,
    { id: PodcastId; episodeId: PodcastId; data: UpdateEpisodeBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateEpisode>>,
  TError,
  { id: PodcastId; episodeId: PodcastId; data: UpdateEpisodeBody },
  TContext
> => {
  const mutationKey = ['updateEpisode'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateEpisode>>,
    { id: PodcastId; episodeId: PodcastId; data: UpdateEpisodeBody }
  > = (props) => {
    const { id, episodeId, data } = props ?? {};

    return updateEpisode(id, episodeId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateEpisodeMutationResult = NonNullable<Awaited<ReturnType<typeof updateEpisode>>>;
export type UpdateEpisodeMutationBody = UpdateEpisodeBody;
export type UpdateEpisodeMutationError = void;

/**
 * @summary Update a podcast episode
 */
export const useUpdateEpisode = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateEpisode>>,
      TError,
      { id: PodcastId; episodeId: PodcastId; data: UpdateEpisodeBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateEpisode>>,
  TError,
  { id: PodcastId; episodeId: PodcastId; data: UpdateEpisodeBody },
  TContext
> => {
  const mutationOptions = getUpdateEpisodeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get a specific podcast episode
 */
export const getEpisode = (id: PodcastId, episodeId: PodcastId, signal?: AbortSignal) => {
  return customAxios<PodcastEpisode>({
    url: `/api/podcasts/${id}/episode/${episodeId}`,
    method: 'GET',
    signal,
  });
};

export const getGetEpisodeQueryKey = (id: PodcastId, episodeId: PodcastId) => {
  return [`/api/podcasts/${id}/episode/${episodeId}`] as const;
};

export const getGetEpisodeQueryOptions = <
  TData = Awaited<ReturnType<typeof getEpisode>>,
  TError = void,
>(
  id: PodcastId,
  episodeId: PodcastId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEpisodeQueryKey(id, episodeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEpisode>>> = ({ signal }) =>
    getEpisode(id, episodeId, signal);

  return { queryKey, queryFn, enabled: !!(id && episodeId), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEpisode>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEpisodeQueryResult = NonNullable<Awaited<ReturnType<typeof getEpisode>>>;
export type GetEpisodeQueryError = void;

export function useGetEpisode<TData = Awaited<ReturnType<typeof getEpisode>>, TError = void>(
  id: PodcastId,
  episodeId: PodcastId,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEpisode>>,
          TError,
          Awaited<ReturnType<typeof getEpisode>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEpisode<TData = Awaited<ReturnType<typeof getEpisode>>, TError = void>(
  id: PodcastId,
  episodeId: PodcastId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEpisode>>,
          TError,
          Awaited<ReturnType<typeof getEpisode>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEpisode<TData = Awaited<ReturnType<typeof getEpisode>>, TError = void>(
  id: PodcastId,
  episodeId: PodcastId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a specific podcast episode
 */

export function useGetEpisode<TData = Awaited<ReturnType<typeof getEpisode>>, TError = void>(
  id: PodcastId,
  episodeId: PodcastId,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEpisode>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetEpisodeQueryOptions(id, episodeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Remove a podcast episode
 */
export const removeEpisode = (
  id: PodcastId,
  episodeId: PodcastId,
  params?: RemoveEpisodeParams
) => {
  return customAxios<Podcast>({
    url: `/api/podcasts/${id}/episode/${episodeId}`,
    method: 'DELETE',
    params,
  });
};

export const getRemoveEpisodeMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeEpisode>>,
    TError,
    { id: PodcastId; episodeId: PodcastId; params?: RemoveEpisodeParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeEpisode>>,
  TError,
  { id: PodcastId; episodeId: PodcastId; params?: RemoveEpisodeParams },
  TContext
> => {
  const mutationKey = ['removeEpisode'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeEpisode>>,
    { id: PodcastId; episodeId: PodcastId; params?: RemoveEpisodeParams }
  > = (props) => {
    const { id, episodeId, params } = props ?? {};

    return removeEpisode(id, episodeId, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveEpisodeMutationResult = NonNullable<Awaited<ReturnType<typeof removeEpisode>>>;

export type RemoveEpisodeMutationError = void;

/**
 * @summary Remove a podcast episode
 */
export const useRemoveEpisode = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeEpisode>>,
      TError,
      { id: PodcastId; episodeId: PodcastId; params?: RemoveEpisodeParams },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof removeEpisode>>,
  TError,
  { id: PodcastId; episodeId: PodcastId; params?: RemoveEpisodeParams },
  TContext
> => {
  const mutationOptions = getRemoveEpisodeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
