/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The full URL where the Apprise API to use is located.
 * @nullable
 */
export type AppriseApiUrl = string | null;
