/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * ID3 metadata tags pulled from the audio file on import. Only non-null tags will be returned in requests.
 */
export interface AudioMetaTags {
  /** @nullable */
  tagAlbum?: string | null;
  /** @nullable */
  tagArtist?: string | null;
  /** @nullable */
  tagGenre?: string | null;
  /** @nullable */
  tagTitle?: string | null;
  /** @nullable */
  tagSeries?: string | null;
  /** @nullable */
  tagSeriesPart?: string | null;
  /** @nullable */
  tagTrack?: string | null;
  /** @nullable */
  tagDisc?: string | null;
  /** @nullable */
  tagSubtitle?: string | null;
  /** @nullable */
  tagAlbumArtist?: string | null;
  /** @nullable */
  tagDate?: string | null;
  /** @nullable */
  tagComposer?: string | null;
  /** @nullable */
  tagPublisher?: string | null;
  /** @nullable */
  tagComment?: string | null;
  /** @nullable */
  tagDescription?: string | null;
  /** @nullable */
  tagEncoder?: string | null;
  /** @nullable */
  tagEncodedBy?: string | null;
  /** @nullable */
  tagIsbn?: string | null;
  /** @nullable */
  tagLanguage?: string | null;
  /** @nullable */
  tagASIN?: string | null;
  /** @nullable */
  tagOverdriveMediaMarker?: string | null;
  /** @nullable */
  tagOriginalYear?: string | null;
  /** @nullable */
  tagReleaseCountry?: string | null;
  /** @nullable */
  tagReleaseType?: string | null;
  /** @nullable */
  tagReleaseStatus?: string | null;
  /** @nullable */
  tagISRC?: string | null;
  /** @nullable */
  tagMusicBrainzTrackId?: string | null;
  /** @nullable */
  tagMusicBrainzAlbumId?: string | null;
  /** @nullable */
  tagMusicBrainzAlbumArtistId?: string | null;
  /** @nullable */
  tagMusicBrainzArtistId?: string | null;
}
