/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AddedAt } from './addedAt';
import type { AudioMetaTags } from './audioMetaTags';
import type { BookChapter } from './bookChapter';
import type { DurationSec } from './durationSec';
import type { FileMetadata } from './fileMetadata';
import type { Inode } from './inode';
import type { UpdatedAt } from './updatedAt';

/**
 * An audio file for a book. Includes audio metadata and track numbers.
 */
export interface AudioFile {
  /** The index of the audio file. */
  index?: number;
  ino?: Inode;
  metadata?: FileMetadata;
  addedAt?: AddedAt;
  updatedAt?: UpdatedAt;
  /**
   * The track number of the audio file as pulled from the file's metadata. Will be null if unknown.
   * @nullable
   */
  trackNumFromMeta?: number | null;
  /**
   * The disc number of the audio file as pulled from the file's metadata. Will be null if unknown.
   * @nullable
   */
  discNumFromMeta?: string | null;
  /**
   * The track number of the audio file as determined from the file's name. Will be null if unknown.
   * @nullable
   */
  trackNumFromFilename?: number | null;
  /**
   * The disc number of the audio file as determined from the file's name. Will be null if unknown.
   * @nullable
   */
  discNumFromFilename?: string | null;
  /** Whether the audio file has been manually verified by a user. */
  manuallyVerified?: boolean;
  /** Whether the audio file is missing from the server. */
  invalid?: boolean;
  /** Whether the audio file has been marked for exclusion. */
  exclude?: boolean;
  /**
   * Any error with the audio file. Will be null if there is none.
   * @nullable
   */
  error?: string | null;
  /** The format of the audio file. */
  format?: string;
  duration?: DurationSec;
  /** The bit rate (in bit/s) of the audio file. */
  bitRate?: number;
  /**
   * The language of the audio file.
   * @nullable
   */
  language?: string | null;
  /** The codec of the audio file. */
  codec?: string;
  /** The time base of the audio file. */
  timeBase?: string;
  /** The number of channels the audio file has. */
  channels?: number;
  /** The layout of the audio file's channels. */
  channelLayout?: string;
  /** If the audio file is part of an audiobook, the chapters the file contains. */
  chapters?: BookChapter[];
  /**
   * The type of embedded cover art in the audio file. Will be null if none exists.
   * @nullable
   */
  embeddedCoverArt?: string | null;
  metaTags?: AudioMetaTags;
  /** The MIME type of the audio file. */
  mimeType?: string;
}
