/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { FileMetadata } from './fileMetadata';

/**
 * Represents an audio track with various properties.
 */
export interface AudioTrack {
  /**
   * The index of the audio track.
   * @nullable
   */
  index?: number | null;
  /**
   * The start offset of the audio track in seconds.
   * @nullable
   */
  startOffset?: number | null;
  /**
   * The duration of the audio track in seconds.
   * @nullable
   */
  duration?: number | null;
  /**
   * The title of the audio track.
   * @nullable
   */
  title?: string | null;
  /**
   * The URL where the audio track content is located.
   * @nullable
   */
  contentUrl?: string | null;
  /**
   * The MIME type of the audio track.
   * @nullable
   */
  mimeType?: string | null;
  /**
   * The codec used for the audio track.
   * @nullable
   */
  codec?: string | null;
  metadata?: FileMetadata;
}
