/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorId } from './authorId';
import type { AuthorAsin } from './authorAsin';
import type { AuthorName } from './authorName';
import type { AuthorDescription } from './authorDescription';
import type { AuthorImagePath } from './authorImagePath';
import type { AddedAt } from './addedAt';
import type { UpdatedAt } from './updatedAt';
import type { LibraryItemMinified } from './libraryItemMinified';
import type { AuthorSeries } from './authorSeries';

/**
 * An author object which includes a description and image path. The library items and series associated with the author are optionally included.
 */
export interface Author {
  id?: AuthorId;
  asin?: AuthorAsin;
  name?: AuthorName;
  description?: AuthorDescription;
  imagePath?: AuthorImagePath;
  addedAt?: AddedAt;
  updatedAt?: UpdatedAt;
  /** The items associated with the author */
  libraryItems?: LibraryItemMinified[];
  /** The series associated with the author */
  series?: AuthorSeries[];
}
