/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

export type AuthorExpandedAllOf = {
  /** The number of books associated with the author in the library. */
  numBooks?: number;
};
