/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * Whether the author was updated without errors. Will not exist if author was merged.
 * @nullable
 */
export type AuthorUpdated = boolean | null;
