/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorId } from './authorId';
import type { AuthorName } from './authorName';

/**
 * Minified author object which only contains the author name and ID.
 */
export interface AuthorMinified {
  id?: AuthorId;
  name?: AuthorName;
}
