/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryItemMinified } from './libraryItemMinified';
import type { SeriesId } from './seriesId';
import type { SeriesName } from './seriesName';

/**
 * Series and the included library items that an author has written.
 */
export interface AuthorSeries {
  id?: SeriesId;
  name?: SeriesName;
  /** The items in the series. Each library item's media's metadata will have a `series` attribute, a `Series Sequence`, which is the matching series. */
  items?: LibraryItemMinified[];
}
