/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The absolute path for the author image. This will be in the `metadata/` directory. Will be null if there is no image.
 * @nullable
 */
export type AuthorImagePath = string | null;
