/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The absolute path on the server of the cover file. Will be null if there is no cover.
 * @nullable
 */
export type BookCoverPath = string | null;
