/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AudioTrack } from './audioTrack';
import type { BookMetadataExpanded } from './bookMetadataExpanded';
import type { DurationSec } from './durationSec';
import type { Size } from './size';

export type BookExpandedAllOf = {
  duration?: DurationSec;
  size?: Size;
  tracks?: AudioTrack[];
  metadata?: BookMetadataExpanded;
};
