/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { TitleIgnorePrefix } from './titleIgnorePrefix';
import type { SchemasAuthorName } from './schemasAuthorName';
import type { AuthorNameLF } from './authorNameLF';
import type { NarratorName } from './narratorName';
import type { SchemasSeriesName } from './schemasSeriesName';

export type BookMetadataMinifiedAllOf = {
  titleIgnorePrefix?: TitleIgnorePrefix;
  authorName?: SchemasAuthorName;
  authorNameLF?: AuthorNameLF;
  narratorName?: NarratorName;
  seriesName?: SchemasSeriesName;
};
