/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { BookMetadataMinified } from './bookMetadataMinified';
import type { BookCoverPath } from './bookCoverPath';
import type { Tags } from './tags';
import type { DurationSec } from './durationSec';
import type { Size } from './size';

/**
 * Minified book schema. Does not depend on `bookBase` because there's pretty much no overlap.
 */
export interface BookMinified {
  metadata?: BookMetadataMinified;
  coverPath?: BookCoverPath;
  tags?: Tags;
  /** The number of tracks the book's audio files have. */
  numTracks?: number;
  /** The number of audio files the book has. */
  numAudioFiles?: number;
  /** The number of chapters the book has. */
  numChapters?: number;
  /** The total number of missing parts the book has. */
  numMissingParts?: number;
  /** The number of invalid audio files the book has. */
  numInvalidAudioFiles?: number;
  duration?: DurationSec;
  size?: Size;
  /**
   * The format of ebook of the book. Will be null if the book is an audiobook.
   * @nullable
   */
  ebookFormat?: string | null;
}
