/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AudioFile } from './audioFile';
import type { BookChapter } from './bookChapter';
import type { BookCoverPath } from './bookCoverPath';
import type { EbookFile } from './ebookFile';
import type { LibraryItemId } from './libraryItemId';
import type { Tags } from './tags';

/**
 * Base book schema
 */
export interface BookBase {
  /** TODO */
  id?: string;
  libraryItemId?: LibraryItemId;
  coverPath?: BookCoverPath;
  tags?: Tags;
  audioFiles?: AudioFile[];
  /** @nullable */
  chapters?: BookChapter[] | null;
  /** Any parts missing from the book by track index. */
  missingParts?: number[];
  ebookFile?: EbookFile;
}
