/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorMinified } from './authorMinified';
import type { SeriesSequence } from './seriesSequence';

export type BookMetadataAllOf = {
  authors?: AuthorMinified[];
  narrators?: string[];
  series?: SeriesSequence[];
};
