/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorName } from './authorName';
import type { SeriesName } from './seriesName';

/**
 * The base book metadata object for minified, normal, and extended schemas to inherit from.
 */
export interface BookMetadataBase {
  /**
   * The title of the book. Will be null if unknown.
   * @nullable
   */
  title?: string | null;
  /**
   * The subtitle of the book. Will be null if there is no subtitle.
   * @nullable
   */
  subtitle?: string | null;
  /** The genres of the book. */
  genres?: string[];
  /**
   * The year the book was published. Will be null if unknown.
   * @nullable
   */
  publishedYear?: string | null;
  /**
   * The date the book was published. Will be null if unknown.
   * @nullable
   */
  publishedDate?: string | null;
  /**
   * The publisher of the book. Will be null if unknown.
   * @nullable
   */
  publisher?: string | null;
  /**
   * A description for the book. Will be null if empty.
   * @nullable
   */
  description?: string | null;
  /**
   * The ISBN of the book. Will be null if unknown.
   * @nullable
   */
  isbn?: string | null;
  /**
   * The ASIN of the book. Will be null if unknown.
   * @nullable
   */
  asin?: string | null;
  /**
   * The language of the book. Will be null if unknown.
   * @nullable
   */
  language?: string | null;
  /** Whether the book has been marked as explicit. */
  explicit?: boolean;
  /** Whether the book is abridged. */
  abridged?: boolean;
  authorName?: AuthorName;
  /** The name of the book's narrator(s). */
  narratorName?: string;
  seriesName?: SeriesName;
}
