/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { BookMetadataBase } from './bookMetadataBase';
import type { BookMetadataMinifiedAllOf } from './bookMetadataMinifiedAllOf';

/**
 * The minified metadata for a book in the database.
 */
export type BookMetadataMinified = BookMetadataBase & BookMetadataMinifiedAllOf;
