/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AutoDownloadEpisodes } from './autoDownloadEpisodes';
import type { FolderId } from './folderId';
import type { LibraryId } from './libraryId';

export type BulkCreatePodcastsFromOpmlFeedUrlsBody = {
  feeds?: string[];
  libraryId?: LibraryId;
  folderId?: FolderId;
  autoDownloadEpisodes?: AutoDownloadEpisodes;
};
