/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { DurationSec } from './durationSec';

export type CloseSessionParams = {
  /**
   * The current time of the session.
   */
  currentTime?: DurationSec;
  /**
   * The time listened to the session.
   */
  timeListened?: DurationSec;
  /**
   * The duration of the session.
   */
  duration?: DurationSec;
};
