/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AppriseApiUrl } from './appriseApiUrl';
import type { MaxFailedAttempts } from './maxFailedAttempts';
import type { MaxNotificationQueue } from './maxNotificationQueue';

export type ConfigureNotificationSettingsBody = {
  appriseApiUrl?: AppriseApiUrl;
  maxFailedAttempts?: MaxFailedAttempts;
  maxNotificationQueue?: MaxNotificationQueue;
};
