/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryIdNullable } from './libraryIdNullable';
import type { NotificationEventName } from './notificationEventName';
import type { Urls } from './urls';
import type { TitleTemplate } from './titleTemplate';
import type { BodyTemplate } from './bodyTemplate';
import type { Enabled } from './enabled';
import type { NotificationType } from './notificationType';

export type CreateNotificationBody = {
  libraryId?: LibraryIdNullable;
  eventName: NotificationEventName;
  urls: Urls;
  titleTemplate: TitleTemplate;
  bodyTemplate: BodyTemplate;
  enabled?: Enabled;
  type?: NotificationType;
};
