/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { ClientName } from './clientName';
import type { ClientVersion } from './clientVersion';
import type { DeviceId } from './deviceId';
import type { Manufacturer } from './manufacturer';
import type { Model } from './model';
import type { SdkVersion } from './sdkVersion';

/**
 * The device information to send to the server.
 */
export interface DeviceInfo {
  deviceId?: DeviceId;
  clientVersion?: ClientVersion;
  clientName?: ClientName;
  manufacturer?: Manufacturer;
  model?: Model;
  sdkVersion?: SdkVersion;
}
