/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { Inode } from './inode';
import type { FileMetadata } from './fileMetadata';
import type { AddedAt } from './addedAt';
import type { UpdatedAt } from './updatedAt';

export interface EbookFile {
  ino?: Inode;
  metadata?: FileMetadata;
  /** The ebook format of the ebook file. */
  ebookFormat?: string;
  addedAt?: AddedAt;
  updatedAt?: UpdatedAt;
}
