/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { EmailSettings } from './emailSettings';

/**
 * Successful response - Email
 */
export type Email200Response = EmailSettings;
