/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { EreaderDeviceObject } from './ereaderDeviceObject';

/**
 * The email settings configuration for the server. This includes the credentials to send e-books and an array of e-reader devices.
 */
export interface EmailSettings {
  /** The unique identifier for the email settings. Currently this is always `email-settings` */
  id: string;
  /**
   * The SMTP host address.
   * @nullable
   */
  host?: string | null;
  /** The port number for the SMTP server. */
  port: number;
  /** Indicates if the connection should use SSL/TLS. */
  secure: boolean;
  /** Indicates if unauthorized SSL/TLS certificates should be rejected. */
  rejectUnauthorized?: boolean;
  /**
   * The username for SMTP authentication.
   * @nullable
   */
  user?: string | null;
  /**
   * The password for SMTP authentication.
   * @nullable
   */
  pass?: string | null;
  /**
   * The test email address used for sending test emails.
   * @nullable
   */
  testAddress?: string | null;
  /**
   * The default "from" email address for outgoing emails.
   * @nullable
   */
  fromAddress?: string | null;
  /** List of configured e-reader devices. */
  ereaderDevices: EreaderDeviceObject[];
}
