/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { EreaderName } from './ereaderName';
import type { EreaderDeviceObjectAvailabilityOption } from './ereaderDeviceObjectAvailabilityOption';

/**
 * An e-reader device configured to receive EPUB through e-mail.
 */
export interface EreaderDeviceObject {
  name: EreaderName;
  /** The email address associated with the e-reader device. */
  email: string;
  /** The availability option for the device. */
  availabilityOption: EreaderDeviceObjectAvailabilityOption;
  /** List of specific users allowed to access the device. */
  users?: string[];
}
