/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The availability option for the device.
 */
export type EreaderDeviceObjectAvailabilityOption =
  (typeof EreaderDeviceObjectAvailabilityOption)[keyof typeof EreaderDeviceObjectAvailabilityOption];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EreaderDeviceObjectAvailabilityOption = {
  adminOrUp: 'adminOrUp',
  userOrUp: 'userOrUp',
  guestOrUp: 'guestOrUp',
  specificUsers: 'specificUsers',
} as const;
