/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * Whether to return Library Item Expanded instead. 0 for false, 1 for true.
 */
export type ExpandedParameter = number;
