/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { Size } from './size';

/**
 * The metadata for a file, including the path, size, and unix timestamps of the file.
 * @nullable
 */
export type FileMetadata = {
  /** The filename of the file. */
  filename?: string;
  /** The file extension of the file. */
  ext?: string;
  /** The absolute path on the server of the file. */
  path?: string;
  /** The path of the file, relative to the book's or podcast's folder. */
  relPath?: string;
  size?: Size;
  /** The time (in ms since POSIX epoch) when the file was last modified on disk. */
  mtimeMs?: number;
  /** The time (in ms since POSIX epoch) when the file status was changed on disk. */
  ctimeMs?: number;
  /** The time (in ms since POSIX epoch) when the file was created on disk. Will be 0 if unknown. */
  birthtimeMs?: number;
} | null;
