/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The time (in ms since POSIX epoch) when the media was finished. Will be null if the media has is not finished.
 * @nullable
 */
export type FinishedAt = number | null;
