/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { FolderId } from './folderId';
import type { LibraryId } from './libraryId';
import type { AddedAt } from './addedAt';

/**
 * Folder used in library
 */
export interface Folder {
  id?: FolderId;
  /** The path on the server for the folder. (Read Only) */
  fullPath?: string;
  libraryId?: LibraryId;
  addedAt?: AddedAt;
}
