/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { ImageWidth } from './imageWidth';
import type { ImageHeight } from './imageHeight';
import type { ImageFormat } from './imageFormat';
import type { ImageRaw } from './imageRaw';

export type GetAuthorImageByIdBody = {
  width?: ImageWidth;
  height?: ImageHeight;
  format?: ImageFormat;
  raw?: ImageRaw;
};
