/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { GetFeedsFromOPMLText200FeedsItem } from './getFeedsFromOPMLText200FeedsItem';

export type GetFeedsFromOPMLText200 = {
  feeds?: GetFeedsFromOPMLText200FeedsItem[];
};
