/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { FilterBy } from './filterBy';
import type { LibraryInclude } from './libraryInclude';
import type { Limit } from './limit';
import type { Minified } from './minified';
import type { Page } from './page';
import type { SeriesBooks } from './seriesBooks';
import type { SortBy } from './sortBy';
import type { SortDesc } from './sortDesc';
import type { Total } from './total';

export type GetLibrarySeries200 = {
  results?: SeriesBooks[];
  total?: Total;
  limit?: Limit;
  page?: Page;
  sortBy?: SortBy;
  sortDesc?: SortDesc;
  filterBy?: FilterBy;
  minified?: Minified;
  include?: LibraryInclude;
};
