/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { GetListeningStats200DayOfWeek } from './getListeningStats200DayOfWeek';
import type { GetListeningStats200Days } from './getListeningStats200Days';
import type { GetListeningStats200Items } from './getListeningStats200Items';
import type { PlaybackSession } from './playbackSession';
import type { TotalTime } from './totalTime';

export type GetListeningStats200 = {
  totalTime?: TotalTime;
  /** A list of library items the user has listened to, keyed by their item IDs. */
  items?: GetListeningStats200Items;
  /** A mapping of days to total listening times. */
  days?: GetListeningStats200Days;
  /** A mapping of days of the week to total listening times. */
  dayOfWeek?: GetListeningStats200DayOfWeek;
  /** The time (in seconds) the user has listened to library items today. */
  today?: number;
  recentSessions?: PlaybackSession[];
};
