/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * A mapping of days to total listening times.
 */
export type GetListeningStats200Days = { [key: string]: number };
