/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { Limit } from './limit';
import type { PlaybackSession } from './playbackSession';
import type { Total } from './total';

export type GetListeningSessions200 = {
  total?: Total;
  /** The number of pages. */
  numPages?: number;
  itemsPerPage?: Limit;
  sessions?: PlaybackSession[];
};
