/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LimitParameter } from './limitParameter';
import type { PageParameter } from './pageParameter';
import type { DescParameter } from './descParameter';
import type { MinifiedParameter } from './minifiedParameter';

export type GetLibraryItemsParams = {
  /**
   * The number of items to return. This the size of a single page for the optional `page` query.
   */
  limit?: LimitParameter;
  /**
   * The page number (zero indexed) to return. If no limit is specified, then page will have no effect.
   */
  page?: PageParameter;
  /**
   * The field to sort by from the request.
   */
  sort?: string;
  /**
   * Return items in reversed order if true.
   */
  desc?: DescParameter;
  /**
   * The filter for the library.
   */
  filter?: string;
  /**
   * The fields to include in the response. The only current option is `rssfeed`.
   */
  include?: string;
  /**
   * Return minified items if true
   */
  minified?: MinifiedParameter;
  /**
   * Whether to collapse series into a single cover
   */
  collapseSeries?: number;
};
