/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

export type GetLibrarySeriesByIdSort =
  (typeof GetLibrarySeriesByIdSort)[keyof typeof GetLibrarySeriesByIdSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetLibrarySeriesByIdSort = {
  name: 'name',
  numBooks: 'numBooks',
  totalDuration: 'totalDuration',
  addedAt: 'addedAt',
  lastBookAdded: 'lastBookAdded',
  lastBookUpdated: 'lastBookUpdated',
} as const;
