/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { EpisodeParameter } from './episodeParameter';
import type { ExpandedParameter } from './expandedParameter';
import type { IncludeParameter } from './includeParameter';

export type GetLibraryItemParams = {
  /**
   * A comma separated list of what to include with the library item. The options are progress, rssfeed, authors (for books), and downloads (for podcasts). expanded must be 1 for include to have an effect.
   */
  include?: IncludeParameter;
  /**
   * Whether to return Library Item Expanded instead. 0 for false, 1 for true.
   */
  expanded?: ExpandedParameter;
  /**
   * If requesting progress for a podcast, the episode ID to get progress for.
   */
  episode?: EpisodeParameter;
};
