/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { Limit } from './limit';
import type { Page } from './page';

export type GetListeningSessionsParams = {
  /**
   * The number of items per page.
   */
  itemsPerPage: Limit;
  /**
   * The page number (zero indexed) to return.
   */
  page: Page;
};
