/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { MinifiedParameter } from './minifiedParameter';

export type GetLibraryByIdParams = {
  /**
   * A comma separated list of what to include with the library item. The only current option is filterdata.
   */
  include?: string;
  /**
   * Return minified items if true
   */
  minified?: MinifiedParameter;
};
