/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { CollapseSeries } from './collapseSeries';
import type { FilterBy } from './filterBy';
import type { LibraryInclude } from './libraryInclude';
import type { LibraryItemBase } from './libraryItemBase';
import type { Limit } from './limit';
import type { MediaType } from './mediaType';
import type { Minified } from './minified';
import type { Page } from './page';
import type { SortBy } from './sortBy';
import type { SortDesc } from './sortDesc';
import type { Total } from './total';

export type GetLibraryItems200 = {
  results?: LibraryItemBase[];
  total?: Total;
  limit?: Limit;
  page?: Page;
  sortBy?: SortBy;
  sortDesc?: SortDesc;
  filterBy?: FilterBy;
  mediaType?: MediaType;
  minified?: Minified;
  collapseSeries?: CollapseSeries;
  include?: LibraryInclude;
};
