/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { NotificationEvent } from './notificationEvent';

export type GetNotifications200Data = {
  events?: NotificationEvent[];
};
