/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from './userId';
import type { Limit } from './limit';
import type { Page } from './page';

export type GetSessionsParams = {
  /**
   * The ID of the user to filter listening sessions by.
   */
  user?: UserId;
  /**
   * The number of items to return.
   */
  itemsPerPage?: Limit;
  /**
   * The page number (zero indexed) to return.
   */
  page?: Page;
};
