/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * A comma separated list of what to include with the series.
 */
export type GetSeriesBodyInclude = (typeof GetSeriesBodyInclude)[keyof typeof GetSeriesBodyInclude];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSeriesBodyInclude = {
  progress: 'progress',
  rssfeed: 'rssfeed',
  'progress,rssfeed': 'progress,rssfeed',
  'rssfeed,progress': 'rssfeed,progress',
} as const;
