/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryItemBase } from './libraryItemBase';
import type { Total } from './total';
import type { Limit } from './limit';
import type { PlaybackSession } from './playbackSession';

export type GetSessions200 = {
  results?: LibraryItemBase[];
  total?: Total;
  itemsPerPage?: Limit;
  /** The number of pages. */
  numPages?: number;
  /** If provided, the `user` parameter. */
  userFilter?: unknown;
  sessions?: PlaybackSession[];
};
