/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { GetSeriesBodyInclude } from './getSeriesBodyInclude';

export type GetSeriesBody = {
  /** A comma separated list of what to include with the series. */
  include?: GetSeriesBodyInclude;
};
