/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The requested height of image in pixels. If `null`, the height is scaled to maintain aspect ratio based on the requested width.
 * @nullable
 */
export type ImageHeight = number | null;
