/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AddedAt } from './addedAt';
import type { FileMetadata } from './fileMetadata';
import type { Inode } from './inode';
import type { UpdatedAt } from './updatedAt';

/**
 * A library file. Includes the path and metadata of the file.
 */
export interface LibraryFile {
  ino?: Inode;
  addedAt?: AddedAt;
  updatedAt?: UpdatedAt;
  /** The type of file. */
  fileType?: string;
  metadata?: FileMetadata;
}
