/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * Preferred metadata provider for the library. See Metadata Providers for a list of possible providers.
 */
export type LibraryProvider = string;
