/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The type of items the shelf contains.
 */
export type LibraryShelfType = (typeof LibraryShelfType)[keyof typeof LibraryShelfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LibraryShelfType = {
  book: 'book',
  podcast: 'podcast',
  series: 'series',
  authors: 'authors',
  episode: 'episode',
} as const;
