/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryShelfEntitiesItem } from './libraryShelfEntitiesItem';
import type { LibraryShelfType } from './libraryShelfType';

/**
 * A library shelf
 */
export interface LibraryShelf {
  /** The ID (Name) of the shelf. */
  id?: string;
  /** The label of the shelf. */
  label?: string;
  /** The localization key for the label. */
  labelStringKey?: string;
  /** The type of items the shelf contains. */
  type?: LibraryShelfType;
  /** The category of the shelf. */
  category?: string;
  /** TODO! I use allOf, because of my programming language , buts a oneOf. It still works with allOf but you will have entries that are not always available. */
  entities?: LibraryShelfEntitiesItem[];
}
