/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorMinified } from './authorMinified';
import type { SeriesNumBooks } from './seriesNumBooks';

export interface LibraryFilterData {
  authors?: AuthorMinified[];
  series?: SeriesNumBooks[];
  tags?: string[];
  genres?: string[];
  narrators?: string[];
  languages?: string[];
}
