/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryItem } from './libraryItem';
import type { LibraryItemShelfAllOf } from './libraryItemShelfAllOf';

/**
 * A single episode of a podcast.
 */
export type LibraryItemShelf = LibraryItem & LibraryItemShelfAllOf;
