/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The fields to include in the response. The only current option is `rssfeed`.
 */
export type LibraryInclude = string;
