/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryItemShelf } from './libraryItemShelf';
import type { SeriesShelf } from './seriesShelf';

export type LibraryShelfEntitiesItem = LibraryItemShelf & SeriesShelf;
