/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryItemId } from './libraryItemId';
import type { OldLibraryItemId } from './oldLibraryItemId';
import type { Inode } from './inode';
import type { LibraryId } from './libraryId';
import type { FolderId } from './folderId';
import type { AddedAt } from './addedAt';
import type { UpdatedAt } from './updatedAt';
import type { MediaType } from './mediaType';
import type { Book } from './book';

/**
 * Base library item schema
 */
export interface LibraryItemBase {
  id?: LibraryItemId;
  oldLibraryItemId?: OldLibraryItemId;
  ino?: Inode;
  libraryId?: LibraryId;
  folderId?: FolderId;
  /** The path of the library item on the server. */
  path?: string;
  /** The path, relative to the library folder, of the library item. */
  relPath?: string;
  /** Whether the library item is a single file in the root of the library folder. */
  isFile?: boolean;
  /** The time (in ms since POSIX epoch) when the library item was last modified on disk. */
  mtimeMs?: number;
  /** The time (in ms since POSIX epoch) when the library item status was changed on disk. */
  ctimeMs?: number;
  /** The time (in ms since POSIX epoch) when the library item was created on disk. Will be 0 if unknown. */
  birthtimeMs?: number;
  addedAt?: AddedAt;
  updatedAt?: UpdatedAt;
  /** Whether the library item was scanned and no longer exists. */
  isMissing?: boolean;
  /** Whether the library item was scanned and no longer has media files. */
  isInvalid?: boolean;
  mediaType?: MediaType;
  media?: Book;
}
