/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The settings for the library.
 */
export interface LibrarySettings {
  /** Whether the library should use square book covers. Must be 0 (for false) or 1 (for true). */
  coverAspectRatio?: number;
  /** Whether to disable the folder watcher for the library. */
  disableWatcher?: boolean;
  /** Whether to skip matching books that already have an ASIN. */
  skipMatchingMediaWithAsin?: boolean;
  /** Whether to skip matching books that already have an ISBN. */
  skipMatchingMediaWithIsbn?: boolean;
  /**
   * The cron expression for when to automatically scan the library folders. If null, automatic scanning will be disabled.
   * @nullable
   */
  autoScanCronExpression?: string | null;
  /** Whether the library should ignore ebook files and only allow ebook files to be supplementary. */
  audiobooksOnly?: boolean;
  /** Whether to hide series with only one book. */
  hideSingleBookSeries?: boolean;
  /** Whether to only show books in a series after the highest series sequence. */
  onlyShowLaterBooksInContinueSeries?: boolean;
  /** The precedence of metadata sources. See Metadata Providers for a list of possible providers. */
  metadataPrecedence?: string[];
  /** The region to use when searching for podcasts. */
  podcastSearchRegion?: string;
}
