/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { Folder } from './folder';

/**
 * The folders of the library. Only specify the fullPath.
 */
export type LibraryFolders = Folder[];
