/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryItemBase } from './libraryItemBase';
import type { LibraryItemAllOf } from './libraryItemAllOf';

/**
 * A single item on the server, like a book or podcast.
 */
export type LibraryItem = LibraryItemBase & LibraryItemAllOf;
