/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryId } from './libraryId';
import type { LibraryName } from './libraryName';
import type { Folder } from './folder';
import type { LibrarySettings } from './librarySettings';
import type { CreatedAt } from './createdAt';
import type { UpdatedAt } from './updatedAt';

/**
 * A library object which includes either books or podcasts.
 */
export interface Library {
  id?: LibraryId;
  name?: LibraryName;
  /** The folders that belong to the library. */
  folders?: Folder[];
  /** Display position of the library in the list of libraries. Must be >= 1. */
  displayOrder?: number;
  /** The selected icon for the library. See Library Icons for a list of possible icons. */
  icon?: string;
  /** The type of media that the library contains. Will be `book` or `podcast`. (Read Only) */
  mediaType?: string;
  /** Preferred metadata provider for the library. See Metadata Providers for a list of possible providers. */
  provider?: string;
  settings?: LibrarySettings;
  createdAt?: CreatedAt;
  lastUpdate?: UpdatedAt;
}
