/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { BookExpanded } from './bookExpanded';
import type { Size } from './size';

export type LibraryItemExpandedAllOf = {
  size?: Size;
  media?: BookExpanded;
};
