/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorSearchName } from './authorSearchName';
import type { AuthorAsin } from './authorAsin';
import type { Region } from './region';

export type MatchAuthorByIdBody = {
  q?: AuthorSearchName;
  asin?: AuthorAsin;
  region?: Region;
};
