/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The maximum number of times a notification fails before being disabled.
 * @minimum 0
 */
export type MaxFailedAttempts = number;
