/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { BookMinified } from './bookMinified';

/**
 * The minified media of the library item.
 */
export type MediaMinified = BookMinified;
