/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The type of media, will be book or podcast.
 */
export type MediaType = (typeof MediaType)[keyof typeof MediaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaType = {
  book: 'book',
  podcast: 'podcast',
} as const;
