/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { BodyTemplate } from './bodyTemplate';
import type { CreatedAt } from './createdAt';
import type { Enabled } from './enabled';
import type { LibraryIdNullable } from './libraryIdNullable';
import type { NotificationEventName } from './notificationEventName';
import type { NotificationId } from './notificationId';
import type { NotificationType } from './notificationType';
import type { TitleTemplate } from './titleTemplate';
import type { Urls } from './urls';

export interface Notification {
  id?: NotificationId;
  libraryId?: LibraryIdNullable;
  eventName?: NotificationEventName;
  urls?: Urls;
  titleTemplate?: TitleTemplate;
  bodyTemplate?: BodyTemplate;
  enabled?: Enabled;
  type?: NotificationType;
  /**
   * The time (in ms since POSIX epoch) when the notification was last fired. Will be null if the notification has not fired.
   * @nullable
   */
  lastFiredAt?: number | null;
  /** Whether the last notification attempt failed. */
  lastAttemptFailed?: boolean;
  /** The number of consecutive times the notification has failed. */
  numConsecutiveFailedAttempts?: number;
  /** The number of times the notification has fired. */
  numTimesFired?: number;
  createdAt?: CreatedAt;
}
