/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

export type NotificationEventDefaults = {
  /** The default title template for notifications using the notification event. */
  title?: string;
  /** The default body template for notifications using the notification event. */
  body?: string;
};
