/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The keys of the testData object will match the list of variables. The values will be the data used when sending a test notification.
 */
export type NotificationEventTestData = { [key: string]: string };
