/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The name of the event the notification will fire on.
 */
export type NotificationEventName =
  (typeof NotificationEventName)[keyof typeof NotificationEventName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationEventName = {
  onPodcastEpisodeDownloaded: 'onPodcastEpisodeDownloaded',
  onTest: 'onTest',
} as const;
