/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { NotificationEventDefaults } from './notificationEventDefaults';
import type { NotificationEventTestData } from './notificationEventTestData';

export interface NotificationEvent {
  /** The name of the notification event. The names and allowable values are defined at https://github.com/advplyr/audiobookshelf/blob/master/server/utils/notifications.js */
  name?: string;
  /** Whether the notification event depends on a library existing. */
  requiresLibrary?: boolean;
  /**
   * The type of media of the library the notification depends on existing. Will not exist if requiresLibrary is false.
   * @nullable
   */
  libraryMediaType?: string | null;
  /** The description of the notification event. */
  description?: string;
  /** The variables of the notification event that can be used in the notification templates. */
  variables?: string[];
  defaults?: NotificationEventDefaults;
  /** The keys of the testData object will match the list of variables. The values will be the data used when sending a test notification. */
  testData?: NotificationEventTestData;
}
