/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AppriseApiUrl } from './appriseApiUrl';
import type { MaxFailedAttempts } from './maxFailedAttempts';
import type { MaxNotificationQueue } from './maxNotificationQueue';
import type { Notification } from './notification';
import type { NotificationId } from './notificationId';

export interface NotificationSettings {
  id?: NotificationId;
  /** The type of Apprise that will be used. At the moment, only api is available. */
  appriseType?: string;
  appriseApiUrl?: AppriseApiUrl;
  /** The set notifications. */
  notifications?: Notification[];
  maxFailedAttempts?: MaxFailedAttempts;
  maxNotificationQueue?: MaxNotificationQueue;
  /** The time (in ms) between notification pushes. */
  notificationDelay?: number;
}
