/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The notification's type.
 * @nullable
 */
export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationType = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  failure: 'failure',
} as const;
