/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The ID of library items on server version 2.2.23 and before.
 * @nullable
 */
export type OldLibraryItemId = string | null;
