/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The page number (zero indexed) to return. If no limit is specified, then page will have no effect.
 */
export type PageParameter = number;
