/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AccessAllLibraries } from './accessAllLibraries';
import type { AccessAllTags } from './accessAllTags';
import type { AccessExplicitContent } from './accessExplicitContent';
import type { Delete } from './delete';
import type { Download } from './download';
import type { Update } from './update';
import type { Upload } from './upload';

export interface Permissions {
  download: Download;
  update: Update;
  delete: Delete;
  upload: Upload;
  accessAllLibraries: AccessAllLibraries;
  accessAllTags: AccessAllTags;
  accessExplicitContent: AccessExplicitContent;
}
