/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

export type PlaybackSessionBookMediaType =
  (typeof PlaybackSessionBookMediaType)[keyof typeof PlaybackSessionBookMediaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlaybackSessionBookMediaType = {
  book: 'book',
} as const;
