/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { PlaybackSessionPodcast } from './playbackSessionPodcast';
import type { PlaybackSessionPodcastExpandedAllOf } from './playbackSessionPodcastExpandedAllOf';
import type { PlaybackSessionPodcastExpandedMediaType } from './playbackSessionPodcastExpandedMediaType';

/**
 * Expanded podcast playback session schema.
 */
export type PlaybackSessionPodcastExpanded = PlaybackSessionPodcast &
  PlaybackSessionPodcastExpandedAllOf & {
    mediaType: PlaybackSessionPodcastExpandedMediaType;
  };
