/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { PlaybackSessionBase } from './playbackSessionBase';
import type { PlaybackSessionPodcastAllOf } from './playbackSessionPodcastAllOf';
import type { PlaybackSessionPodcastMediaType } from './playbackSessionPodcastMediaType';

/**
 * Podcast playback session schema.
 */
export type PlaybackSessionPodcast = PlaybackSessionBase &
  PlaybackSessionPodcastAllOf & {
    mediaType: PlaybackSessionPodcastMediaType;
  } & Required<
    Pick<
      PlaybackSessionBase &
        PlaybackSessionPodcastAllOf & {
          mediaType: PlaybackSessionPodcastMediaType;
        },
      'mediaType'
    >
  >;
