/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The video track of the media. TODO
 * @nullable
 */
export type PlaybackSessionBookExpandedAllOfVideoTrack = { [key: string]: unknown } | null;
