/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { PlaybackSessionBook } from './playbackSessionBook';
import type { PlaybackSessionBookExpandedAllOf } from './playbackSessionBookExpandedAllOf';
import type { PlaybackSessionBookExpandedMediaType } from './playbackSessionBookExpandedMediaType';

/**
 * Expanded book playback session schema.
 */
export type PlaybackSessionBookExpanded = PlaybackSessionBook &
  PlaybackSessionBookExpandedAllOf & {
    mediaType: PlaybackSessionBookExpandedMediaType;
  };
