/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { DeviceInfo } from './deviceInfo';
import type { ForceDirectPlay } from './forceDirectPlay';
import type { ForceTranscode } from './forceTranscode';
import type { SupportedMimeTypes } from './supportedMimeTypes';
import type { MediaPlayer } from './mediaPlayer';

export type PlayLibraryItemPodcastEpisodeBody = {
  deviceInfo?: DeviceInfo;
  forceDirectPlay?: ForceDirectPlay;
  forceTranscode?: ForceTranscode;
  supportedMimeTypes?: SupportedMimeTypes;
  mediaPlayer?: MediaPlayer;
};
