/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { PodcastId } from './podcastId';
import type { PodcastMetadata } from './podcastMetadata';

export type PlaybackSessionPodcastAllOf = {
  mediaMetadata?: PodcastMetadata;
  episodeId?: PodcastId;
};
