/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { PlaybackSessionBook } from './playbackSessionBook';
import type { PlaybackSessionPodcast } from './playbackSessionPodcast';

/**
 * A playback session object.
 */
export type PlaybackSession = PlaybackSessionBook | PlaybackSessionPodcast;
