/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { BookCoverPath } from './bookCoverPath';
import type { CreatedAt } from './createdAt';
import type { DeviceInfo } from './deviceInfo';
import type { DurationSec } from './durationSec';
import type { LibraryId } from './libraryId';
import type { LibraryItemId } from './libraryItemId';
import type { MediaType } from './mediaType';
import type { PlaybackSessionId } from './playbackSessionId';
import type { ServerVersion } from './serverVersion';
import type { UpdatedAt } from './updatedAt';
import type { UserId } from './userId';

/**
 * Base playback session object.
 */
export interface PlaybackSessionBase {
  id?: PlaybackSessionId;
  userId?: UserId;
  libraryId?: LibraryId;
  libraryItemId?: LibraryItemId;
  mediaType?: MediaType;
  /** The display title of the media. */
  displayTitle?: string;
  /** The display author of the media. */
  displayAuthor?: string;
  coverPath?: BookCoverPath;
  duration?: DurationSec;
  /** The method used to play the media. 0 = Direct play, 1 = Direct Stream, 2 = Transcode, 3 = Local */
  playMethod?: number;
  /** The media player used to play the media. */
  mediaPlayer?: string;
  deviceInfo?: DeviceInfo;
  serverVersion?: ServerVersion;
  /** TODO */
  date?: string;
  /** TODO */
  dayOfWeek?: string;
  timeListening?: DurationSec;
  startTime?: DurationSec;
  currentTime?: DurationSec;
  createdAt?: CreatedAt;
  updatedAt?: UpdatedAt;
}
