/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AudioTrack } from './audioTrack';
import type { LibraryItem } from './libraryItem';
import type { PlaybackSessionPodcastExpandedAllOfVideoTrack } from './playbackSessionPodcastExpandedAllOfVideoTrack';

export type PlaybackSessionPodcastExpandedAllOf = {
  /** The audio tracks of the media. */
  audioTracks?: AudioTrack[];
  /**
   * The video track of the media. TODO
   * @nullable
   */
  videoTrack?: PlaybackSessionPodcastExpandedAllOfVideoTrack;
  libraryItem?: LibraryItem;
};
