/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { BookMetadata } from './bookMetadata';
import type { BookChapter } from './bookChapter';

export type PlaybackSessionBookAllOf = {
  mediaMetadata?: BookMetadata;
  /** The chapters of the media. */
  chapters?: BookChapter[];
};
