/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

export type PlaybackSessionBookExpandedMediaType =
  (typeof PlaybackSessionBookExpandedMediaType)[keyof typeof PlaybackSessionBookExpandedMediaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlaybackSessionBookExpandedMediaType = {
  book: 'book',
} as const;
