/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { PlaybackSessionBase } from './playbackSessionBase';
import type { PlaybackSessionBookAllOf } from './playbackSessionBookAllOf';
import type { PlaybackSessionBookMediaType } from './playbackSessionBookMediaType';

/**
 * Book playback session schema.
 */
export type PlaybackSessionBook = PlaybackSessionBase &
  PlaybackSessionBookAllOf & {
    mediaType: PlaybackSessionBookMediaType;
  } & Required<
    Pick<
      PlaybackSessionBase &
        PlaybackSessionBookAllOf & {
          mediaType: PlaybackSessionBookMediaType;
        },
      'mediaType'
    >
  >;
