/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { PlaybackSessionBookExpanded } from './playbackSessionBookExpanded';
import type { PlaybackSessionPodcastExpanded } from './playbackSessionPodcastExpanded';

/**
 * A playback session object.
 */
export type PlaybackSessionExpanded = PlaybackSessionBookExpanded | PlaybackSessionPodcastExpanded;
