/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * The enclosure object containing additional episode data.
 * @nullable
 */
export type PodcastEpisodeEnclosure = { [key: string]: unknown } | null;
