/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { PodcastId } from './podcastId';
import type { LibraryItemId } from './libraryItemId';
import type { PodcastMetadata } from './podcastMetadata';
import type { PodcastEpisode } from './podcastEpisode';
import type { AutoDownloadEpisodes } from './autoDownloadEpisodes';

/**
 * A podcast containing multiple episodes.
 */
export interface Podcast {
  id?: PodcastId;
  libraryItemId?: LibraryItemId;
  metadata?: PodcastMetadata;
  /**
   * The file path to the podcast's cover image.
   * @nullable
   */
  coverPath?: string | null;
  /** The tags associated with the podcast. */
  tags?: string[];
  /** The episodes of the podcast. */
  episodes?: PodcastEpisode[];
  autoDownloadEpisodes?: AutoDownloadEpisodes;
  /**
   * The schedule for automatic episode downloads, in cron format.
   * @nullable
   */
  autoDownloadSchedule?: string | null;
  /** The timestamp of the last episode check. */
  lastEpisodeCheck?: number;
  /** The maximum number of episodes to keep. */
  maxEpisodesToKeep?: number;
  /** The maximum number of new episodes to download when automatically downloading epsiodes. */
  maxNewEpisodesToDownload?: number;
  /**
   * The timestamp of the last cover search.
   * @nullable
   */
  lastCoverSearch?: number | null;
  /**
   * The query used for the last cover search.
   * @nullable
   */
  lastCoverSearchQuery?: string | null;
  /** The total size of all episodes in bytes. */
  size?: number;
  /** The total duration of all episodes in seconds. */
  duration?: number;
  /** The number of tracks (episodes) in the podcast. */
  numTracks?: number;
  /** The timestamp of the most recently published episode. */
  latestEpisodePublished?: number;
}
