/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata for a podcast.
 */
export interface PodcastMetadata {
  /**
   * The title of the podcast.
   * @nullable
   */
  title?: string | null;
  /**
   * The author of the podcast.
   * @nullable
   */
  author?: string | null;
  /**
   * The description of the podcast.
   * @nullable
   */
  description?: string | null;
  /**
   * The release date of the podcast.
   * @nullable
   */
  releaseDate?: string | null;
  /** The genres of the podcast. */
  genres?: string[];
  /**
   * The URL of the podcast feed.
   * @nullable
   */
  feedUrl?: string | null;
  /**
   * The URL of the podcast's image.
   * @nullable
   */
  imageUrl?: string | null;
  /**
   * The URL of the podcast's iTunes page.
   * @nullable
   */
  itunesPageUrl?: string | null;
  /**
   * The iTunes ID of the podcast.
   * @nullable
   */
  itunesId?: string | null;
  /**
   * The iTunes artist ID of the podcast.
   * @nullable
   */
  itunesArtistId?: string | null;
  /** Whether the podcast contains explicit content. */
  explicit?: boolean;
  /**
   * The language of the podcast.
   * @nullable
   */
  language?: string | null;
  /**
   * The type of podcast (e.g., episodic, serial).
   * @nullable
   */
  type?: string | null;
}
