/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryItemId } from './libraryItemId';
import type { PodcastId } from './podcastId';
import type { OldPodcastId } from './oldPodcastId';
import type { PodcastEpisodeEnclosure } from './podcastEpisodeEnclosure';
import type { PodcastEpisodeChaptersItem } from './podcastEpisodeChaptersItem';
import type { AudioFile } from './audioFile';
import type { CreatedAt } from './createdAt';
import type { AddedAt } from './addedAt';
import type { UpdatedAt } from './updatedAt';
import type { AudioTrack } from './audioTrack';
import type { DurationSec } from './durationSec';
import type { Size } from './size';

/**
 * A single episode of a podcast.
 */
export interface PodcastEpisode {
  libraryItemId?: LibraryItemId;
  podcastId?: PodcastId;
  id?: PodcastId;
  oldEpisodeId?: OldPodcastId;
  /**
   * The index of the episode within the podcast.
   * @nullable
   */
  index?: number | null;
  /**
   * The season number of the episode.
   * @nullable
   */
  season?: string | null;
  /**
   * The episode number within the season.
   * @nullable
   */
  episode?: string | null;
  /**
   * The type of episode (e.g., full, trailer).
   * @nullable
   */
  episodeType?: string | null;
  /**
   * The title of the episode.
   * @nullable
   */
  title?: string | null;
  /**
   * The subtitle of the episode.
   * @nullable
   */
  subtitle?: string | null;
  /**
   * The description of the episode.
   * @nullable
   */
  description?: string | null;
  /**
   * The enclosure object containing additional episode data.
   * @nullable
   */
  enclosure?: PodcastEpisodeEnclosure;
  /**
   * The globally unique identifier for the episode.
   * @nullable
   */
  guid?: string | null;
  /**
   * The publication date of the episode.
   * @nullable
   */
  pubDate?: string | null;
  /** The chapters within the episode. */
  chapters?: PodcastEpisodeChaptersItem[];
  audioFile?: AudioFile;
  publishedAt?: CreatedAt;
  addedAt?: AddedAt;
  updatedAt?: UpdatedAt;
  audioTrack?: AudioTrack;
  duration?: DurationSec;
  size?: Size;
}
