/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LimitParameter } from './limitParameter';

export type SearchLibraryParams = {
  /**
   * The search query.
   */
  q: string;
  /**
   * The number of items to return. This the size of a single page for the optional `page` query.
   */
  limit?: LimitParameter;
};
