/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */

export type SendDefaultTestNotificationParams = {
  /**
   * Whether to intentionally cause the notification to fail. `0` for false, `1` for true.
   */
  fail?: number;
};
