/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AddedAt } from './addedAt';
import type { SeriesDescription } from './seriesDescription';
import type { SeriesId } from './seriesId';
import type { SeriesName } from './seriesName';
import type { UpdatedAt } from './updatedAt';

/**
 * A series object which includes the name and description of the series.
 */
export interface Series {
  id?: SeriesId;
  name?: SeriesName;
  description?: SeriesDescription;
  addedAt?: AddedAt;
  updatedAt?: UpdatedAt;
}
