/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { SeriesId } from './seriesId';
import type { SeriesName } from './seriesName';
import type { Sequence } from './sequence';

/**
 * A series object which includes the name and sequence of the series.
 */
export interface SeriesSequence {
  id?: SeriesId;
  name?: SeriesName;
  sequence?: Sequence;
}
