/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { SeriesId } from './seriesId';
import type { SeriesName } from './seriesName';
import type { LibraryItemId } from './libraryItemId';

/**
 * A series object which includes the name and number of books in the series.
 */
export interface SeriesNumBooks {
  id?: SeriesId;
  name?: SeriesName;
  /** The number of books in the series. */
  numBooks?: number;
  /** The IDs of the library items in the series. */
  libraryItemIds?: LibraryItemId[];
}
