/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryItemId } from './libraryItemId';

/**
 * The user's progress of a series.
 */
export interface SeriesProgress {
  /** The IDs of the library items in the series. */
  libraryItemIds?: LibraryItemId[];
  /** The IDs of the library items in the series that are finished. */
  libraryItemIdsFinished?: LibraryItemId[];
  /** Whether the series is finished. */
  isFinished?: boolean;
}
