/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { SeriesId } from './seriesId';
import type { SeriesName } from './seriesName';
import type { AddedAt } from './addedAt';
import type { LibraryItemSequence } from './libraryItemSequence';

/**
 * A series object which includes the name and books in the series.
 */
export interface SeriesBooks {
  id?: SeriesId;
  name?: SeriesName;
  addedAt?: AddedAt;
  /** The name of the series with any prefix moved to the end. */
  nameIgnorePrefix?: string;
  /** The name of the series with any prefix removed. */
  nameIgnorePrefixSort?: string;
  /** Will always be `series`. */
  type?: string;
  /** The library items that contain the books in the series. A sequence attribute that denotes the position in the series the book is in, is tacked on. */
  books?: LibraryItemSequence[];
  /** The combined duration (in seconds) of all books in the series. */
  totalDuration?: number;
}
