/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryItemMinified } from './libraryItemMinified';

/**
 * @nullable
 */
export type SeriesShelfAllOf = {
  books?: LibraryItemMinified[];
  /**
   * Whether the user has started listening to the series.
   * @nullable
   */
  inProgress?: boolean | null;
  /**
   * Whether the user has started listening to the series, but has not finished it.
   * @nullable
   */
  hasActiveBook?: boolean | null;
  /**
   * Whether the series should be hidden from the continue listening section.
   * @nullable
   */
  hideFromContinueListening?: boolean | null;
  /**
   * An Integer, the time (in ms since POSIX epoch) when the book's progress was last updated.
   * @nullable
   */
  bookInProgressLastUpdate?: number | null;
  firstBookUnread?: LibraryItemMinified;
} | null;
