/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { DurationSec } from './durationSec';
import type { PlaybackSessionId } from './playbackSessionId';

export type SyncOpenSessionBody = {
  id?: PlaybackSessionId;
  currentTime?: DurationSec;
  timeListened?: DurationSec;
  duration?: DurationSec;
};
