/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { Author } from './author';
import type { AuthorUpdated } from './authorUpdated';
import type { AuthorMerged } from './authorMerged';

export type UpdateAuthorById200 = Author | AuthorUpdated | AuthorMerged;
