/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorName } from './authorName';
import type { AuthorDescription } from './authorDescription';
import type { AuthorImagePath } from './authorImagePath';
import type { AuthorAsin } from './authorAsin';

export type UpdateAuthorByIdBody = {
  name?: AuthorName;
  description?: AuthorDescription;
  imagePath?: AuthorImagePath;
  asin?: AuthorAsin;
};
