/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Audiobookshelf API
 * Audiobookshelf API with autogenerated OpenAPI doc
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryName } from './libraryName';
import type { LibraryFolders } from './libraryFolders';
import type { LibraryDisplayOrder } from './libraryDisplayOrder';
import type { LibraryIcon } from './libraryIcon';
import type { LibraryMediaType } from './libraryMediaType';
import type { LibraryProvider } from './libraryProvider';
import type { LibrarySettings } from './librarySettings';

export type UpdateLibraryByIdBody = {
  name?: LibraryName;
  folders?: LibraryFolders;
  displayOrder?: LibraryDisplayOrder;
  icon?: LibraryIcon;
  mediaType?: LibraryMediaType;
  provider?: LibraryProvider;
  settings?: LibrarySettings;
};
